"""Shared banner/comment formatting helpers."""

from __future__ import annotations
import os
import datetime

from ..graph import OnnxGraph
from ..nodes import OP_NAMES, MatmulNode


def _banner(title: str) -> str:
    bar = "/" * 72
    return f"\n{bar}\n/* {title:<68} */\n{bar}\n"


def _file_banner(filename: str, graph: OnnxGraph, model_path: str) -> str:
    ts         = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    model_name = os.path.basename(model_path)
    n_nodes    = len(graph.nodes)

    # Collect op names: VectorOP codes for ScheduledNode, "MatMul" for MatmulNode
    ops_used = sorted({
        "MatMul" if isinstance(sn, MatmulNode) else OP_NAMES[sn.op_code]
        for sn in graph.nodes
    })
    ops_str = ", ".join(ops_used) if ops_used else "(none)"

    # Identify which kernel(s) are used
    has_matmul   = any(isinstance(sn, MatmulNode) for sn in graph.nodes)
    has_vectorop = any(not isinstance(sn, MatmulNode) for sn in graph.nodes)
    if has_matmul and has_vectorop:
        kernel_line = "MatmulKernel (matrix multiply) + VectorOPKernel (element-wise)"
    elif has_matmul:
        kernel_line = "MatmulKernel (matrix multiply, tiled)"
    else:
        kernel_line = "VectorOPKernel (element-wise, 1-D, II=1)"

    lines = [
        "/*",
        f" * {filename}",
        f" * Auto-generated by inference-scheduler",
        f" * Source model : {model_name}",
        f" * Generated at : {ts}",
        f" * Scheduled ops: {n_nodes}",
        f" * Op codes used: {ops_str}",
        " *",
    ]
    for t in graph.input_tensors:
        lines.append(f" * Input  : {t.onnx_name}  shape={t.shape}  numel={t.numel}")
    for t in graph.output_tensors:
        lines.append(f" * Output : {t.onnx_name}  shape={t.shape}  numel={t.numel}")
    lines += [
        " *",
        " * Target: Xilinx KV260 bare-metal, ap_fixed<16,8> data type",
        f" * Kernel: {kernel_line}",
        " */",
    ]
    return "\n".join(lines)
