# Vitis HLS synthesis script — generated by CMake from Synthesis.tcl.in
# Runs C synthesis and exports the result as a Vivado IP catalog entry.
#
# Variables substituted by CMake configure_file:
#   VA_HLS_PROJECT_NAME    — HLS project directory name
#   VA_PART_NAME           — FPGA part string (e.g. xck26-sfvc784-2LV-c)
#   VA_BOARD_OPTION        — set_part command (includes -board if available)
#   VA_SRC_SYNTHESIS       — space-separated list of kernel source files
#   VA_SYNTHESIS_FLAGS_PLATFORM — compiler flags including -I paths
#   VA_TARGET_CLOCK_TCL    — target clock period in MHz
#   VA_IP_OUTPUT_DIR       — output directory for the exported IP catalog

open_project vadd_kv260
open_solution solution1 -flow_target vivado

set_part {xck26-sfvc784-2LV-c} -board {xilinx.com:kv260_som:part0:1.4}

add_files -cflags "-O3 -DVA_SYNTHESIS -I/home/ivan/projects/axi_demo/kernels/vectorop/include -I/home/ivan/projects/axi_demo/kernels/vectorop/kv260" "/home/ivan/projects/axi_demo/kernels/vectorop/kernel/VectorOP.cpp"
set_top VectorOPKernel

create_clock -period 300MHz -name default

config_interface -m_axi_addr64
config_interface -m_axi_max_widen_bitwidth 32
config_rtl -reset_level low

csynth_design
export_design -format ip_catalog -output /home/ivan/projects/axi_demo/kernels/vectorop/kv260/ip_catalog

exit
