"""
C code generator for the inference scheduler.

CodeGenerator produces three files for an inference project:

  generate_header()  →  include/inference.h
      Public API: Data_t typedef, array-size macros,
      inference_init() and inference_run() declarations.

  generate_source()  →  src/inference.c
      Implementation: weight arrays, intermediate buffers,
      static run_op() helper, inference_init(), inference_run().
      Includes "inference.h" for the shared type and declarations.

  generate_cmake()   →  CMakeLists.txt
      Builds a static library 'inference' from src/inference.c
      and the XVectoropkernel driver sources in driver/.

The generated code targets the Xilinx KV260 (bare-metal and Linux):
  - XVectoropkernel driver API  (driver/xvectoropkernel.h)
  - Xil cache maintenance API   (xil_cache.h, from BSP; no-op on Linux)
  - DMA-capable buffers via inference_buf_t (src/inference_buf.c)
  - ap_fixed<16,8> element type

Physical-address model
----------------------
VectorOPKernel's AXI master ports read/write DDR using physical addresses
stored in AXI-Lite registers (Set_a / Set_b / Set_c).  On Linux, virtual
pointers from malloc/stack are NOT valid DDR addresses.

inference_buf_t abstracts this:
  - Linux:      dma-proxy pool; physical address from /proc/self/pagemap
                (requires root; dma_alloc_coherent memory is contiguous).
  - Bare-metal: malloc (virtual == physical on Xilinx standalone).

inference_buf_phys() returns the physical address to program into the kernel
registers; inference_buf_ptr() returns the virtual pointer for CPU access.
"""

from __future__ import annotations
import os
import datetime
from typing import List

from .graph  import OnnxGraph
from .tensor import TensorInfo, LARGE_WEIGHT_THRESHOLD
from .nodes  import OP_NAMES


# ------------------------------------------------------------------ #
# Formatting helpers                                                  #
# ------------------------------------------------------------------ #

def _banner(title: str) -> str:
    bar = "/" * 72
    return f"\n{bar}\n/* {title:<68} */\n{bar}\n"


def _file_banner(filename: str, graph: OnnxGraph, model_path: str) -> str:
    ts         = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    model_name = os.path.basename(model_path)
    n_nodes    = len(graph.nodes)
    ops_used   = sorted({OP_NAMES[sn.op_code] for sn in graph.nodes})
    ops_str    = ", ".join(ops_used) if ops_used else "(none)"

    lines = [
        "/*",
        f" * {filename}",
        f" * Auto-generated by inference-scheduler",
        f" * Source model : {model_name}",
        f" * Generated at : {ts}",
        f" * Scheduled ops: {n_nodes}",
        f" * Op codes used: {ops_str}",
        " *",
    ]
    for t in graph.input_tensors:
        lines.append(f" * Input  : {t.onnx_name}  shape={t.shape}  numel={t.numel}")
    for t in graph.output_tensors:
        lines.append(f" * Output : {t.onnx_name}  shape={t.shape}  numel={t.numel}")
    lines += [
        " *",
        " * Target: Xilinx KV260 bare-metal, ap_fixed<16,8> data type",
        " * Kernel: VectorOPKernel (element-wise, 1-D, II=1)",
        " */",
    ]
    return "\n".join(lines)


# ------------------------------------------------------------------ #
# CodeGenerator                                                       #
# ------------------------------------------------------------------ #

class CodeGenerator:
    def __init__(self, graph: OnnxGraph, model_path: str,
                 embed_large_weights: bool = False) -> None:
        self._graph               = graph
        self._model_path          = model_path
        self._embed_large_weights = embed_large_weights

    # ---------------------------------------------------------------- #
    # Public entry points                                               #
    # ---------------------------------------------------------------- #

    def generate_header(self) -> str:
        """Content for include/inference.h."""
        parts = [
            _file_banner("inference.h", self._graph, self._model_path),
            self._header_guard_open(),
            self._header_api(),
            self._header_guard_close(),
        ]
        return "\n".join(parts) + "\n"

    def generate_source(self) -> str:
        """Content for src/inference.c."""
        parts = [
            _file_banner("inference.c", self._graph, self._model_path),
            self._source_includes(),
            self._source_op_defines(),
            self._weight_arrays(),
            self._buffer_declarations(),
            self._kernel_instance(),
            self._run_op_helper(),
            self._init_function(),
            self._inference_function(),
        ]
        return "\n".join(parts) + "\n"

    def generate_buf_impl(self) -> str:
        """Content for src/inference_buf.c.

        Platform-independent public API (accessors) plus two platform
        implementations selected at compile time by __linux__:
          - Linux:      posix_memalign + mlock + /proc/self/pagemap (root).
                        No special device needed; each buffer is independent.
          - Bare-metal: malloc (virtual address == physical address on Xilinx
                        standalone/FreeRTOS BSP).
        """
        return (
            _file_banner("inference_buf.c", self._graph, self._model_path) +
            _BUF_IMPL_TEMPLATE
        )

    def generate_setup_script(self) -> str:
        """Content for scripts/check_inference_setup.sh."""
        pool_bytes = self._compute_pool_bytes()
        model_name = os.path.basename(self._model_path)
        return _SETUP_SCRIPT_TEMPLATE.format(
            model_name=model_name,
            pool_bytes=pool_bytes,
        )

    def generate_test(self) -> str:
        """Content for test/test_inference.c — one-shot smoke test.

        Allocates input/output DMA buffers, fills inputs with a ramp
        (element i = i/256.0 in ap_fixed<16,8> encoding), runs inference,
        and prints the first 8 output values.  Exit code 0 = success.
        """
        graph   = self._graph
        inputs  = graph.input_tensors
        outputs = graph.output_tensors

        # Variable declarations at top of main()
        decl_lines = []
        for t in inputs + outputs:
            decl_lines.append(f"    inference_buf_t *{t.c_name} = NULL;")

        # Buffer allocations with goto-cleanup error handling.
        # Each failure jumps to 'cleanup' which frees all I/O buffers
        # (NULL-safe) and calls inference_deinit(), so no buffer leaks.
        alloc_lines = []
        for t in inputs + outputs:
            macro = f"INFERENCE_{t.c_name.upper()}_SIZE"
            alloc_lines.append(f"    {t.c_name} = inference_buf_alloc({macro});")
            alloc_lines.append(f"    if (!{t.c_name}) {{")
            alloc_lines.append(
                f"        fprintf(stderr, "
                f"\"inference_buf_alloc failed for '{t.c_name}'\\n\");"
            )
            alloc_lines.append("        rc = 1; goto cleanup;")
            alloc_lines.append("    }")

        # Fill each input with a ramp: raw uint16 value i = i/256.0
        fill_lines = []
        for t in inputs:
            macro = f"INFERENCE_{t.c_name.upper()}_SIZE"
            fill_lines += [
                f"    {{",
                f"        Data_t *p = inference_buf_ptr({t.c_name});",
                f"        for (i = 0; i < {macro}; i++)",
                f"            p[i] = (Data_t)(i & 0xFFFFu); /* i/256.0 */",
                f"    }}",
            ]

        # inference_run() call
        run_args = ", ".join(t.c_name for t in inputs + outputs)

        # Print first ≤8 elements of each output
        print_lines = []
        for t in outputs:
            macro = f"INFERENCE_{t.c_name.upper()}_SIZE"
            print_lines += [
                f"    {{",
                f"        Data_t   *p   = inference_buf_ptr({t.c_name});",
                f"        unsigned  lim = ({macro} < 8u) ? {macro} : 8u;",
                f"        printf(\"Output '{t.onnx_name}'"
                f" (%u elem, first %u):\\n\", (unsigned){macro}, lim);",
                f"        for (i = 0; i < lim; i++) {{",
                f"            int16_t s = (int16_t)p[i];",
                f"            printf(\"  [%u] 0x%04X  (%.4f)\\n\",",
                f"                   i, (unsigned)p[i], (double)s / 256.0);",
                f"        }}",
                f"    }}",
            ]

        # Cleanup label: free all I/O buffers (NULL-safe), then deinit.
        cleanup_lines = []
        for t in inputs + outputs:
            cleanup_lines.append(f"    inference_buf_free({t.c_name});")

        decl_str    = "\n".join(decl_lines)
        alloc_str   = "\n".join(alloc_lines)
        fill_str    = "\n".join(fill_lines) if fill_lines else "    /* (no inputs) */"
        print_str   = "\n".join(print_lines)
        cleanup_str = "\n".join(cleanup_lines)

        return (
            _file_banner("test_inference.c", graph, self._model_path) +
            "\n"
            "#include <stdio.h>\n"
            "#include \"inference.h\"\n"
            "\n"
            "/*\n"
            " * Default hardware instance passed to inference_init().\n"
            " *   Linux:      UIO device (see /sys/class/uio/ for the right index)\n"
            " *   Bare-metal: device name string from xparameters.h\n"
            " * Override: cmake -DINFERENCE_TEST_INSTANCE=\\\"/dev/uio1\\\"\n"
            " *       or: ./test_inference /dev/uio1\n"
            " */\n"
            "#ifndef INFERENCE_TEST_INSTANCE\n"
            "#  ifdef __linux__\n"
            "#    define INFERENCE_TEST_INSTANCE  \"/dev/uio0\"\n"
            "#  else\n"
            "#    define INFERENCE_TEST_INSTANCE  \"VectorOPKernel\"\n"
            "#  endif\n"
            "#endif\n"
            "\n"
            "int main(int argc, char **argv)\n"
            "{\n"
            "    const char *instance = (argc > 1) ? argv[1]\n"
            "                                      : INFERENCE_TEST_INSTANCE;\n"
            f"{decl_str}\n"
            "    unsigned i;\n"
            "    int      rc = 0;\n"
            "\n"
            "    /* 1. Initialise: open UIO device, map DMA pool */\n"
            "    rc = inference_init(instance);\n"
            "    if (rc != 0) {\n"
            "        fprintf(stderr, \"inference_init(\\\"%s\\\") failed: %d\\n\",\n"
            "                instance, rc);\n"
            "        return 1;\n"
            "    }\n"
            "    printf(\"inference_init OK (\\\"%s\\\")\\n\", instance);\n"
            "\n"
            "    /* 2. Allocate I/O buffers from the DMA pool */\n"
            f"{alloc_str}\n"
            "\n"
            "    /* 3. Fill inputs: ramp pattern (element i = i/256.0) */\n"
            f"{fill_str}\n"
            "\n"
            "    /* 4. Run inference */\n"
            f"    inference_run({run_args});\n"
            "\n"
            "    /* 5. Print first 8 output elements */\n"
            f"{print_str}\n"
            "\n"
            "    if (rc == 0)\n"
            "        printf(\"test_inference PASSED\\n\");\n"
            "\n"
            "    /* 6. Teardown — reached on both success and alloc failure */\n"
            "cleanup:\n"
            f"{cleanup_str}\n"
            "    inference_deinit();\n"
            "    return rc;\n"
            "}\n"
        )

    def generate_cmake(self) -> str:
        """Content for CMakeLists.txt."""
        inputs  = self._graph.input_tensors
        outputs = self._graph.output_tensors
        in_desc  = ", ".join(f"{t.onnx_name}{t.shape}" for t in inputs)
        out_desc = ", ".join(f"{t.onnx_name}{t.shape}" for t in outputs)
        model_basename = os.path.basename(self._model_path)

        return (
            f"# CMakeLists.txt — auto-generated by inference-scheduler\n"
            f"# Model  : {model_basename}\n"
            f"# Input  : {in_desc}\n"
            f"# Output : {out_desc}\n"
            f"#\n"
            f"# Builds a static library 'inference' from src/inference.c and the\n"
            f"# XVectoropkernel driver sources in driver/.\n"
            f"#\n"
            f"# Two targets are supported via the INFERENCE_TARGET cache variable:\n"
            f"#\n"
            f"#   BARE_METAL (default)\n"
            f"#     Cross-compile for Xilinx standalone / FreeRTOS BSP.\n"
            f"#     Requires -DBSP_INCLUDE_DIR=<path> and an aarch64-none-elf toolchain.\n"
            f"#     Driver:  driver/xvectoropkernel_sinit.c  (static device lookup)\n"
            f"#     Cache:   Xil_DCacheFlushRange / Xil_DCacheInvalidateRange\n"
            f"#\n"
            f"#   LINUX\n"
            f"#     Build natively on KV260 Linux (or cross-compile with aarch64-linux-gnu).\n"
            f"#     No BSP required; uses the UIO mmap driver and standard libc.\n"
            f"#     Driver:  driver/xvectoropkernel_linux.c  (open/mmap /dev/uioX)\n"
            f"#     Cache:   no-op (KV260 HPC ports are hardware cache-coherent)\n"
            f"#\n"
            f"# Usage — BARE_METAL:\n"
            f"#   cmake -S . -B build-bm \\\n"
            f"#     -DINFERENCE_TARGET=BARE_METAL \\\n"
            f"#     -DCMAKE_TOOLCHAIN_FILE=<toolchain-aarch64-none-elf.cmake> \\\n"
            f"#     -DBSP_INCLUDE_DIR=<bsp>/psu_cortexa53_0/include\n"
            f"#   cmake --build build-bm\n"
            f"#\n"
            f"# Usage — LINUX:\n"
            f"#   cmake -S . -B build-linux -DINFERENCE_TARGET=LINUX\n"
            f"#   cmake --build build-linux\n"
            f"\n"
            f"cmake_minimum_required(VERSION 3.19)\n"
            f"project(inference VERSION 1.0 LANGUAGES C)\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Target selection\n"
            f"# -----------------------------------------------------------------------\n"
            f"set(INFERENCE_TARGET \"BARE_METAL\" CACHE STRING\n"
            f"    \"Build target: BARE_METAL (standalone BSP) or LINUX (UIO mmap)\")\n"
            f"set_property(CACHE INFERENCE_TARGET PROPERTY STRINGS BARE_METAL LINUX)\n"
            f"\n"
            f"if(NOT INFERENCE_TARGET STREQUAL \"BARE_METAL\" AND\n"
            f"   NOT INFERENCE_TARGET STREQUAL \"LINUX\")\n"
            f"    message(FATAL_ERROR\n"
            f"        \"INFERENCE_TARGET must be BARE_METAL or LINUX, \"\n"
            f"        \"got '${{INFERENCE_TARGET}}'\")\n"
            f"endif()\n"
            f"\n"
            f"message(STATUS \"inference: building for target ${{INFERENCE_TARGET}}\")\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Verify common driver sources\n"
            f"# (copy from <axi_demo>/build/kv260/vadd_kv260/solution1/impl/ip/\n"
            f"#             drivers/VectorOPKernel_v1_0/src/ or see driver/README.md)\n"
            f"# -----------------------------------------------------------------------\n"
            f"foreach(_drv\n"
            f"        driver/xvectoropkernel.c\n"
            f"        driver/xvectoropkernel.h\n"
            f"        driver/xvectoropkernel_hw.h)\n"
            f"    if(NOT EXISTS \"${{CMAKE_CURRENT_SOURCE_DIR}}/${{_drv}}\")\n"
            f"        message(FATAL_ERROR\n"
            f"            \"Driver file not found: ${{_drv}}\\n\"\n"
            f"            \"Populate driver/ — see driver/README.md\")\n"
            f"    endif()\n"
            f"endforeach()\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Target-specific driver source + include/link settings\n"
            f"# -----------------------------------------------------------------------\n"
            f"if(INFERENCE_TARGET STREQUAL \"BARE_METAL\")\n"
            f"\n"
            f"    set(_TARGET_DRIVER driver/xvectoropkernel_sinit.c)\n"
            f"    if(NOT EXISTS \"${{CMAKE_CURRENT_SOURCE_DIR}}/${{_TARGET_DRIVER}}\")\n"
            f"        message(FATAL_ERROR\n"
            f"            \"BARE_METAL: driver file not found: ${{_TARGET_DRIVER}}\")\n"
            f"    endif()\n"
            f"\n"
            f"    if(NOT BSP_INCLUDE_DIR)\n"
            f"        message(WARNING\n"
            f"            \"BARE_METAL: BSP_INCLUDE_DIR is not set.\\n\"\n"
            f"            \"Set it to the Vitis standalone BSP include directory, e.g.:\\n\"\n"
            f"            \"  cmake -DBSP_INCLUDE_DIR=<bsp>/psu_cortexa53_0/include\")\n"
            f"    endif()\n"
            f"    set(_TARGET_INCDIRS ${{BSP_INCLUDE_DIR}})\n"
            f"\n"
            f"else() # LINUX\n"
            f"\n"
            f"    set(_TARGET_DRIVER driver/xvectoropkernel_linux.c)\n"
            f"    if(NOT EXISTS \"${{CMAKE_CURRENT_SOURCE_DIR}}/${{_TARGET_DRIVER}}\")\n"
            f"        message(FATAL_ERROR\n"
            f"            \"LINUX: driver file not found: ${{_TARGET_DRIVER}}\")\n"
            f"    endif()\n"
            f"\n"
            f"    # XRT runtime — provides xclAllocBO/xclSyncBO/xclMapBO for DMA buffers.\n"
            f"    # Locate XRT via pkg-config (preferred) or a manual XRT_DIR fallback.\n"
            f"    find_package(PkgConfig QUIET)\n"
            f"    if(PkgConfig_FOUND)\n"
            f"        pkg_check_modules(XRT QUIET xrt)\n"
            f"    endif()\n"
            f"\n"
            f"    if(XRT_FOUND)\n"
            f"        message(STATUS \"inference: XRT found via pkg-config (${{XRT_VERSION}})\")\n"
            f"        set(_TARGET_INCDIRS ${{XRT_INCLUDE_DIRS}})\n"
            f"        set(_TARGET_LIBS    ${{XRT_LIBRARIES}})\n"
            f"    else()\n"
            f"        # Fallback: manual prefix (e.g. cross-compile or no pkg-config)\n"
            f"        set(XRT_DIR \"/opt/xilinx/xrt\" CACHE PATH\n"
            f"            \"XRT installation prefix, used when pkg-config cannot find xrt\")\n"
            f"        if(NOT EXISTS \"${{XRT_DIR}}/include/xrt.h\")\n"
            f"            message(WARNING\n"
            f"                \"XRT not found via pkg-config and header missing at \"\n"
            f"                \"${{XRT_DIR}}/include/xrt.h\\n\"\n"
            f"                \"Install XRT or set -DXRT_DIR=<prefix>.\")\n"
            f"        endif()\n"
            f"        set(_TARGET_INCDIRS ${{XRT_DIR}}/include)\n"
            f"        set(_TARGET_LIBS    ${{XRT_DIR}}/lib/libxrt_core.so)\n"
            f"    endif()\n"
            f"\n"
            f"endif()\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Static library\n"
            f"# -----------------------------------------------------------------------\n"
            f"add_library(inference STATIC\n"
            f"    src/inference.c\n"
            f"    src/inference_buf.c\n"
            f"    driver/xvectoropkernel.c\n"
            f"    ${{_TARGET_DRIVER}}\n"
            f")\n"
            f"\n"
            f"target_include_directories(inference\n"
            f"    PUBLIC  ${{CMAKE_CURRENT_SOURCE_DIR}}/include\n"
            f"    PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}}/driver\n"
            f"    PRIVATE ${{_TARGET_INCDIRS}}\n"
            f")\n"
            f"\n"
            f"target_compile_options(inference PRIVATE -Wall -Wextra -O2)\n"
            f"\n"
            f"if(DEFINED _TARGET_LIBS)\n"
            f"    target_link_libraries(inference PUBLIC ${{_TARGET_LIBS}})\n"
            f"endif()\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# External weight files (.dat) — loaded at runtime by inference_init()\n"
            f"# -----------------------------------------------------------------------\n"
            f"# INFERENCE_WEIGHTS_DIR is the directory that contains the weights/\n"
            f"# subdirectory at runtime (where the binary looks for *.dat files).\n"
            f"# Defaults to the build directory; override for install targets.\n"
            f"set(INFERENCE_WEIGHTS_DIR \"${{CMAKE_CURRENT_SOURCE_DIR}}\"\n"
            f"    CACHE PATH \"Runtime directory that contains the weights/ subdirectory\")\n"
            f"target_compile_definitions(inference PRIVATE\n"
            f"    INFERENCE_WEIGHTS_DIR=\"${{INFERENCE_WEIGHTS_DIR}}\")\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Install\n"
            f"# -----------------------------------------------------------------------\n"
            f"install(TARGETS inference ARCHIVE DESTINATION lib)\n"
            f"install(FILES include/inference.h DESTINATION include)\n"
            f"install(DIRECTORY weights/ DESTINATION weights\n"
            f"    FILES_MATCHING PATTERN \"*.dat\")\n"
            f"\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Smoke test (requires hardware to run; built by default)\n"
            f"# -----------------------------------------------------------------------\n"
            f"# Allocates DMA buffers, fills inputs with a ramp, runs one forward\n"
            f"# pass, and prints the first 8 output values.  Not registered with\n"
            f"# CTest because it needs the physical VectorOPKernel IP.\n"
            f"#\n"
            f"# Build only (no hardware needed):\n"
            f"#   cmake --build <builddir> --target test_inference\n"
            f"# Run on target:\n"
            f"#   ./test_inference              # uses /dev/uio0 (Linux default)\n"
            f"#   ./test_inference /dev/uio1    # custom UIO device\n"
            f"# Disable: cmake -DINFERENCE_BUILD_TEST=OFF ...\n"
            f"option(INFERENCE_BUILD_TEST\n"
            f"       \"Build test_inference smoke test\" ON)\n"
            f"if(INFERENCE_BUILD_TEST)\n"
            f"    add_executable(test_inference test/test_inference.c)\n"
            f"    target_link_libraries(test_inference PRIVATE inference)\n"
            f"    target_compile_options(test_inference PRIVATE -Wall -Wextra -O2)\n"
            f"    message(STATUS\n"
            f"        \"inference: test_inference will be built \"\n"
            f"        \"(disable: -DINFERENCE_BUILD_TEST=OFF)\")\n"
            f"endif()\n"
        )

    # ---------------------------------------------------------------- #
    # Header sections                                                   #
    # ---------------------------------------------------------------- #

    def _header_guard_open(self) -> str:
        return (
            "\n#pragma once\n"
            "\n#ifdef __cplusplus\n"
            "extern \"C\" {\n"
            "#endif\n"
            "\n#include <stdint.h>\n"
        )

    def _header_guard_close(self) -> str:
        return "\n#ifdef __cplusplus\n}\n#endif\n"

    def _compute_pool_bytes(self) -> int:
        """
        Total DMA memory needed for all model buffers, with 64-byte alignment
        per buffer, rounded up to a 4 KiB page boundary.

        Covers: weight tensors + intermediate tensors + model inputs + outputs.
        Used to size the u-dma-buf pool and advertised as
        INFERENCE_BUF_POOL_SIZE_BYTES in the generated header.
        """
        def _align64(n: int) -> int:
            return (n + 63) & ~63

        total = 0
        for t in (self._graph.weight_tensors
                  + self._graph.intermediate_tensors
                  + self._graph.input_tensors
                  + self._graph.output_tensors):
            total += _align64(t.numel * 2)   # INFERENCE_BYTES_PER_ELEM = 2

        page = 4096
        return (total + page - 1) & ~(page - 1)

    @property
    def large_weight_tensors(self) -> List[TensorInfo]:
        """Weight tensors stored as external .dat files.
        Empty when embed_large_weights=True (all weights inlined)."""
        if self._embed_large_weights:
            return []
        return [t for t in self._graph.weight_tensors if t.is_large_weight]

    def generate_weight_dat(self, tensor: TensorInfo) -> bytes:
        """
        Return the raw binary content for weights/<c_name>.dat.
        Little-endian uint16 values in the same ap_fixed<16,8> encoding
        used by the C ROM arrays, suitable for fread() at runtime.
        """
        return tensor.to_dat_bytes()

    def _header_api(self) -> str:
        graph   = self._graph
        inputs  = graph.input_tensors
        outputs = graph.output_tensors

        lines = [_banner("Data type")]
        lines.append(
            "/* ap_fixed<16,8>: 16-bit two's-complement, value = (int16_t)bits / 256.0 */"
        )
        lines.append("typedef uint16_t Data_t;")
        lines.append("#define INFERENCE_BYTES_PER_ELEM  2u")
        lines.append("")

        # Array-size macros — let callers size their buffers without magic numbers
        lines.append(_banner("Array size constants"))
        for t in inputs:
            macro = f"INFERENCE_{t.c_name.upper()}_SIZE"
            lines.append(f"#define {macro:<40} {t.numel}u  /* shape={t.shape} */")
        for t in outputs:
            macro = f"INFERENCE_{t.c_name.upper()}_SIZE"
            lines.append(f"#define {macro:<40} {t.numel}u  /* shape={t.shape} */")

        # DMA buffer pool size
        pool_bytes = self._compute_pool_bytes()
        lines.append(_banner("DMA buffer pool"))
        lines.append(
            "/*\n"
            " * Minimum contiguous DMA pool required for this model.\n"
            " *\n"
            " * Linux:      run scripts/check_inference_setup.sh before the\n"
            " *             application to verify root access and pagemap\n"
            " *             availability (required for physical address lookup).\n"
            " * Bare-metal: pool is not used; each buffer is allocated from\n"
            " *             the heap individually.\n"
            " */"
        )
        lines.append(
            f"#define INFERENCE_BUF_POOL_SIZE_BYTES  {pool_bytes}u"
        )
        lines.append("")

        # DMA buffer API
        lines.append(_banner("DMA-capable buffer API"))
        lines.append(
            "/* Opaque DMA-capable buffer handle.\n"
            " * Always allocate with inference_buf_alloc(); never create on the stack.\n"
            " * Physical address (for kernel DMA registers) and virtual address (for\n"
            " * CPU access) are managed internally. */"
        )
        lines.append("typedef struct inference_buf inference_buf_t;")
        lines.append("")
        lines.append(
            "/* Allocate a buffer for n_elem Data_t elements from the DMA pool.\n"
            " * Returns NULL on failure.  On Linux the bump allocator never frees\n"
            " * individual sub-allocations; call inference_deinit() to release all. */"
        )
        lines.append("inference_buf_t *inference_buf_alloc(unsigned n_elem);")
        lines.append("")
        lines.append(
            "/* Release a buffer.  Bare-metal: frees heap memory.\n"
            " * Linux: frees the struct metadata only (pool memory released at deinit). */"
        )
        lines.append("void  inference_buf_free(inference_buf_t *buf);")
        lines.append("")
        lines.append(
            "/* CPU-accessible virtual pointer to the buffer data. */"
        )
        lines.append("Data_t  *inference_buf_ptr(inference_buf_t *buf);")
        lines.append("")
        lines.append(
            "/* Physical DDR address — write this value into AXI-Lite DMA registers. */"
        )
        lines.append("uint64_t inference_buf_phys(const inference_buf_t *buf);")
        lines.append("")
        lines.append(
            "/* Number of Data_t elements that were allocated. */"
        )
        lines.append("unsigned inference_buf_count(const inference_buf_t *buf);")
        lines.append("")
        lines.append(
            "/* Sync buffer to device — flush CPU cache before the PL kernel reads.\n"
            " * Called automatically by inference_run(); exposed for manual control. */"
        )
        lines.append("void inference_buf_sync_to_device(inference_buf_t *buf);")
        lines.append("")
        lines.append(
            "/* Sync buffer from device — invalidate CPU cache after the PL kernel writes.\n"
            " * Called automatically by inference_run(); exposed for manual control. */"
        )
        lines.append("void inference_buf_sync_from_device(inference_buf_t *buf);")
        lines.append("")
        lines.append(
            "/* Fill n elements of buf from a float array.\n"
            " * Each value is cast to Data_t using C's built-in conversion.\n"
            " * n must be <= inference_buf_count(buf). */"
        )
        lines.append(
            "void inference_buf_fill_float(inference_buf_t *buf,"
            " const float *src, unsigned n);"
        )
        lines.append("")
        lines.append(
            "/* Read n elements from buf into a float array.\n"
            " * Each Data_t element is cast to float using C's built-in conversion.\n"
            " * n must be <= inference_buf_count(buf). */"
        )
        lines.append(
            "void inference_buf_read_float(const inference_buf_t *buf,"
            " float *dst, unsigned n);"
        )
        lines.append("")

        # inference_init()
        lines.append(_banner("Inference API"))
        lines.append(
            "/*\n"
            " * inference_init() — initialise the DMA pool, weight buffers,\n"
            " *                    and the XVectoropkernel driver.\n"
            " *\n"
            " * instance_name  bare-metal: device name string (see xparameters.h)\n"
            " *                Linux:      UIO device path, e.g. \"/dev/uio0\"\n"
            " *\n"
            " * Returns 0 on success, non-zero on failure.\n"
            " */"
        )
        lines.append("int  inference_init(const char *instance_name);")
        lines.append("")
        lines.append(
            "/*\n"
            " * inference_deinit() — release all DMA buffers and the pool.\n"
            " * Call once when the inference library is no longer needed.\n"
            " */"
        )
        lines.append("void inference_deinit(void);")
        lines.append("")

        # inference_run()
        params = []
        for t in inputs:
            params.append(f"    inference_buf_t *{t.c_name}")
        for t in outputs:
            params.append(f"    inference_buf_t *{t.c_name}")

        doc_lines = [
            "/*",
            " * inference_run() — execute the full inference graph.",
            " *",
            " *   Buffers must be allocated with inference_buf_alloc().",
            " *   Fill input buffers via inference_buf_ptr() before calling.",
            " *",
        ]
        for t in inputs:
            doc_lines.append(
                f" *   {t.c_name:<22} [in]   inference_buf_t*  "
                f"({t.numel} elem, shape={t.shape})"
            )
        for t in outputs:
            doc_lines.append(
                f" *   {t.c_name:<22} [out]  inference_buf_t*  "
                f"({t.numel} elem, shape={t.shape})"
            )
        doc_lines.append(" */")

        lines.append("\n".join(doc_lines))
        lines.append(
            "void inference_run(\n"
            + ",\n".join(params)
            + ");"
        )

        return "\n".join(lines)

    # ---------------------------------------------------------------- #
    # Source sections                                                   #
    # ---------------------------------------------------------------- #

    def _source_includes(self) -> str:
        stdio = '#include <stdio.h>    /* fopen, fread, snprintf */\n' \
                if self.large_weight_tensors else ''
        return (
            _banner("Includes") +
            '#include "inference.h"\n'
            '#include "xvectoropkernel.h"\n'
            '#include <string.h>    /* memcpy */\n'
            f'{stdio}'
            '\n'
            '/*\n'
            ' * Cache coherency between the CPU and the AXI DMA master is handled by\n'
            ' * inference_buf_sync_to_device() and inference_buf_sync_from_device(),\n'
            ' * both implemented in inference_buf.c:\n'
            ' *\n'
            ' *   Linux:      xclSyncBO (XRT) — XCL_BO_SYNC_BO_TO/FROM_DEVICE\n'
            ' *   Bare-metal: Xil_DCacheFlushRange / Xil_DCacheInvalidateRange\n'
            ' */\n'
            '\n'
            '/* Forward declarations — defined in inference_buf.c */\n'
            'void inference_buf_sync_to_device(inference_buf_t *buf);\n'
            'void inference_buf_sync_from_device(inference_buf_t *buf);\n'
        )

    def _source_op_defines(self) -> str:
        lines = [_banner("VectorOPKernel operation codes (must match VectorOP.h)")]
        for code, name in sorted(OP_NAMES.items()):
            lines.append(f"#define {name:<20} {code}u")
        return "\n".join(lines)

    def _weight_arrays(self) -> str:
        weights = self._graph.weight_tensors
        if not weights:
            return ""
        external = {t.onnx_name for t in self.large_weight_tensors}
        parts = [_banner("Constant weight arrays (ONNX initializers)")]
        for t in weights:
            if t.onnx_name in external:
                parts.append(t.emit_large_weight_ptr_decl())
            else:
                parts.append(t.emit_weight_decl())
            parts.append("")
        return "\n".join(parts)

    def _buffer_declarations(self) -> str:
        lines = [_banner("Mutable intermediate buffers")]

        for t in self._graph.input_tensors:
            lines.append(f"/* INPUT  '{t.onnx_name}'  shape={t.shape} — caller-supplied */")
        for t in self._graph.output_tensors:
            lines.append(f"/* OUTPUT '{t.onnx_name}'  shape={t.shape} — caller-supplied */")
        lines.append("")

        intermediates = self._graph.intermediate_tensors
        if intermediates:
            for t in intermediates:
                lines.append(t.emit_buffer_decl())
        else:
            lines.append("/* (no intermediate buffers) */")

        return "\n".join(lines)

    def _kernel_instance(self) -> str:
        return (
            _banner("Kernel driver instance") +
            "static XVectoropkernel s_kernel;\n"
        )

    def _run_op_helper(self) -> str:
        return (
            _banner("run_op() — configure and execute one VectorOPKernel call") +
            "/*\n"
            " * run_op() — program AXI-Lite registers with physical addresses,\n"
            " *             maintain cache coherence, start the kernel, and poll.\n"
            " *\n"
            " * The kernel's AXI master reads/writes DDR using PHYSICAL addresses;\n"
            " * inference_buf_phys() provides the address to program into the registers.\n"
            " * inference_buf_ptr() provides the virtual address for CPU cache ops.\n"
            " *\n"
            " *   a     input buffer A  (always required)\n"
            " *   b     input buffer B  (NULL for unary ops: RELU, RELU6)\n"
            " *   c     output buffer C (must not alias a or b)\n"
            " *   size  number of elements\n"
            " *   op    VECTOROP_* constant\n"
            " */\n"
            "static void run_op(\n"
            "    inference_buf_t *a,\n"
            "    inference_buf_t *b,\n"
            "    inference_buf_t *c,\n"
            "    unsigned         size,\n"
            "    unsigned         op)\n"
            "{\n"
            "    XVectoropkernel_Set_a(&s_kernel, inference_buf_phys(a));\n"
            "    XVectoropkernel_Set_b(&s_kernel, b ? inference_buf_phys(b) : (u64)0);\n"
            "    XVectoropkernel_Set_c(&s_kernel, inference_buf_phys(c));\n"
            "    XVectoropkernel_Set_size(&s_kernel, size);\n"
            "    XVectoropkernel_Set_op(&s_kernel, op);\n"
            "\n"
            "    /* Sync inputs: flush CPU cache / XRT BO to device before AXI master reads */\n"
            "    inference_buf_sync_to_device(a);\n"
            "    if (b != NULL)\n"
            "        inference_buf_sync_to_device(b);\n"
            "\n"
            "    XVectoropkernel_Start(&s_kernel);\n"
            "    while (!XVectoropkernel_IsDone(&s_kernel)) {}\n"
            "\n"
            "    /* Sync output: invalidate CPU cache / XRT BO from device after AXI master writes */\n"
            "    inference_buf_sync_from_device(c);\n"
            "}\n"
        )

    def _load_weight_helper(self) -> str:
        """
        Emit the _load_weight() helper used by inference_init() to read a .dat
        file into a DMA buffer.  Only included when the model has large weights.
        """
        return (
            _banner("_load_weight() — read an external weight .dat file") +
            "/*\n"
            " * _load_weight() — open weights/<name>.dat and fread() its contents\n"
            " * directly into the DMA buffer.  The .dat file contains raw little-\n"
            " * endian uint16 values in the same ap_fixed<16,8> encoding used by\n"
            " * the inline ROM arrays.\n"
            " *\n"
            " * INFERENCE_WEIGHTS_DIR is set by CMake (default \".\").\n"
            " * Override at configure time: cmake -DINFERENCE_WEIGHTS_DIR=/path/to/weights\n"
            " */\n"
            "#ifndef INFERENCE_WEIGHTS_DIR\n"
            "#  define INFERENCE_WEIGHTS_DIR  \".\"\n"
            "#endif\n"
            "\n"
            "static int _load_weight(inference_buf_t *buf,\n"
            "                        const char *name, unsigned n_elem)\n"
            "{\n"
            "    char path[512];\n"
            "    FILE *f;\n"
            "    size_t n_read;\n"
            "\n"
            "    snprintf(path, sizeof(path),\n"
            "             INFERENCE_WEIGHTS_DIR \"/weights/%s.dat\", name);\n"
            "    f = fopen(path, \"rb\");\n"
            "    if (!f) {\n"
            '        fprintf(stderr,\n'
            '                "inference: cannot open weight file \'%s\'\\n", path);\n'
            "        return -1;\n"
            "    }\n"
            "    n_read = fread(inference_buf_ptr(buf),\n"
            "                  INFERENCE_BYTES_PER_ELEM, n_elem, f);\n"
            "    fclose(f);\n"
            "    if (n_read != (size_t)n_elem) {\n"
            '        fprintf(stderr,\n'
            '                "inference: short read from \'%s\':"\n'
            '                " got %zu, expected %u\\n",\n'
            '                path, n_read, n_elem);\n'
            "        return -1;\n"
            "    }\n"
            "    return 0;\n"
            "}\n"
        )

    def _init_function(self) -> str:
        graph         = self._graph
        weights       = graph.weight_tensors
        intermediates = graph.intermediate_tensors

        alloc_lines: List[str] = []

        if weights:
            external = {t.onnx_name for t in self.large_weight_tensors}
            alloc_lines.append(
                "    /* Allocate DMA buffers for weights */"
            )
            for t in weights:
                alloc_lines.append(
                    f"    {t.c_name} = inference_buf_alloc({t.numel}u);"
                )
                alloc_lines.append(
                    f"    if (!{t.c_name}) {{ rc = -1; goto fail; }}"
                )
                if t.onnx_name in external:
                    alloc_lines.append(
                        f"    if (_load_weight({t.c_name},"
                        f" \"{t.c_name}\", {t.numel}u) != 0) {{ rc = -1; goto fail; }}"
                    )
                else:
                    alloc_lines.append(
                        f"    memcpy(inference_buf_ptr({t.c_name}),"
                        f" _rom_{t.c_name}, sizeof(_rom_{t.c_name}));"
                    )
            alloc_lines.append("")

        if intermediates:
            alloc_lines.append("    /* Allocate intermediate buffers */")
            for t in intermediates:
                alloc_lines.append(
                    f"    {t.c_name} = inference_buf_alloc({t.numel}u);"
                )
                alloc_lines.append(
                    f"    if (!{t.c_name}) {{ rc = -1; goto fail; }}"
                )
            alloc_lines.append("")

        alloc_str = ("\n".join(alloc_lines) + "\n") if alloc_lines else ""

        # inference_deinit(): free owned buffers (safe on NULL), then close pool.
        # Buffers must be freed before inference_buf_pool_deinit() because the
        # Linux/XRT path needs the device handle open to call xclFreeBO().
        deinit_free: List[str] = []
        for t in weights + intermediates:
            deinit_free.append(
                f"    inference_buf_free({t.c_name}); {t.c_name} = NULL;"
            )
        deinit_body = ("\n".join(deinit_free) + "\n") if deinit_free else ""

        load_helper = self._load_weight_helper() if self.large_weight_tensors else ""

        return (
            load_helper +
            _banner("inference_init() / inference_deinit()") +
            "/* Internal: pool lifecycle — defined in inference_buf.c */\n"
            "int  inference_buf_pool_init(void);\n"
            "void inference_buf_pool_deinit(void);\n"
            "\n"
            "int inference_init(const char *instance_name)\n"
            "{\n"
            "    int rc;\n"
            "\n"
            "    /* Initialise DMA buffer pool */\n"
            "    rc = inference_buf_pool_init();\n"
            "    if (rc != 0) return rc;\n"
            "\n"
            f"{alloc_str}"
            "    /* Initialise kernel driver */\n"
            "    rc = XVectoropkernel_Initialize(&s_kernel, instance_name);\n"
            "    if (rc != 0) goto fail;\n"
            "    return 0;\n"
            "\n"
            "fail:\n"
            "    inference_deinit();\n"
            "    return rc;\n"
            "}\n"
            "\n"
            "void inference_deinit(void)\n"
            "{\n"
            f"{deinit_body}"
            "    inference_buf_pool_deinit();\n"
            "}\n"
        )

    def _inference_function(self) -> str:
        graph   = self._graph
        inputs  = graph.input_tensors
        outputs = graph.output_tensors

        params = []
        for t in inputs:
            params.append(f"    inference_buf_t *{t.c_name}")
        for t in outputs:
            params.append(f"    inference_buf_t *{t.c_name}")
        param_str = ",\n".join(params)

        body_lines = []
        for sn in graph.nodes:
            body_lines.append(sn.emit_comment())
            body_lines.append(sn.emit_call())
            body_lines.append("")
        if body_lines and body_lines[-1] == "":
            body_lines.pop()
        body = "\n".join(body_lines) if body_lines else "    /* (empty graph) */"

        return (
            _banner("inference_run()") +
            "void inference_run(\n"
            f"{param_str})\n"
            "{\n"
            f"{body}\n"
            "}\n"
        )


# ------------------------------------------------------------------ #
# Static templates for generated files                                #
# ------------------------------------------------------------------ #

# inference_buf.c — dual-platform DMA buffer allocator.
# The file banner (with model info / timestamp) is prepended by
# generate_buf_impl().  INFERENCE_BYTES_PER_ELEM comes from inference.h.
_BUF_IMPL_TEMPLATE = r"""
////////////////////////////////////////////////////////////////////////
/* inference_buf_t definition                                          */
////////////////////////////////////////////////////////////////////////

#include "inference.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

struct inference_buf {
    void    *virt;    /* CPU-accessible virtual address */
    uint64_t phys;    /* physical DDR address for AXI DMA registers */
    unsigned  count;  /* number of Data_t elements allocated */
#ifdef __linux__
    unsigned  bo;     /* XRT buffer object handle (xclBufferHandle = unsigned) */
#endif
};

////////////////////////////////////////////////////////////////////////
/* Platform-independent accessors                                      */
////////////////////////////////////////////////////////////////////////

Data_t *inference_buf_ptr(inference_buf_t *buf)
{
    return (Data_t *)buf->virt;
}

uint64_t inference_buf_phys(const inference_buf_t *buf)
{
    return buf->phys;
}

unsigned inference_buf_count(const inference_buf_t *buf)
{
    return buf->count;
}

////////////////////////////////////////////////////////////////////////
/* Float cast helpers (platform-independent)                           */
/*                                                                     */
/* Uses C's built-in implicit conversion to/from Data_t so the        */
/* implementation is correct for any numeric Data_t (float, double,   */
/* int8_t, int16_t, uint8_t, …) without type-specific constants.      */
////////////////////////////////////////////////////////////////////////

void inference_buf_fill_float(inference_buf_t *buf,
                              const float *src, unsigned n)
{
    Data_t  *dst = (Data_t *)buf->virt;
    unsigned i;
    for (i = 0; i < n; i++)
        dst[i] = (Data_t)src[i];
}

void inference_buf_read_float(const inference_buf_t *buf,
                              float *dst, unsigned n)
{
    const Data_t *src = (const Data_t *)buf->virt;
    unsigned i;
    for (i = 0; i < n; i++)
        dst[i] = (float)src[i];
}

////////////////////////////////////////////////////////////////////////
/* Linux — XRT Buffer Object (BO) API                                 */
/*                                                                     */
/* xclAllocBO allocates DMA-coherent memory managed by the XRT        */
/* runtime.  xclGetBOProperties.paddr is the physical device address  */
/* to program into the AXI-Lite DMA registers.                         */
/*                                                                     */
/* xclSyncBO handles cache coherency via the XRT DMA engine:           */
/*   XCL_BO_SYNC_BO_TO_DEVICE   — flush before kernel reads inputs    */
/*   XCL_BO_SYNC_BO_FROM_DEVICE — invalidate after kernel writes out  */
/*                                                                     */
/* Mirrors PYNQ xrt_device.py allocate_bo / map_bo /                  */
/*   get_device_address / flush / invalidate.                          */
/*                                                                     */
/* Requires XRT runtime (/opt/xilinx/xrt) and access to the XRT       */
/* device node.                                                        */
////////////////////////////////////////////////////////////////////////

#ifdef __linux__

#include <stdio.h>
#include <xrt.h>

static xclDeviceHandle s_xrt_dev = NULL;

int inference_buf_pool_init(void)
{
    s_xrt_dev = xclOpen(0, NULL, (enum xclVerbosityLevel)XCL_QUIET);
    if (s_xrt_dev == NULL) {
        fprintf(stderr, "inference: xclOpen(0) failed — is XRT loaded?\n");
        return -1;
    }
    return 0;
}

void inference_buf_pool_deinit(void)
{
    if (s_xrt_dev) {
        xclClose(s_xrt_dev);
        s_xrt_dev = NULL;
    }
}

inference_buf_t *inference_buf_alloc(unsigned n_elem)
{
    size_t                 bytes = (size_t)n_elem * INFERENCE_BYTES_PER_ELEM;
    xclBufferHandle        bo;
    void                  *virt;
    struct xclBOProperties props;
    inference_buf_t       *buf;

    buf = (inference_buf_t *)malloc(sizeof(inference_buf_t));
    if (!buf) return NULL;

    /* flags = 0: XCL_BO_FLAGS_NONE — regular DMA-coherent host buffer */
    bo = xclAllocBO(s_xrt_dev, bytes, 0, 0);
    if (bo == (xclBufferHandle)NULLBO) {
        fprintf(stderr, "inference: xclAllocBO(%zu bytes) failed\n", bytes);
        free(buf);
        return NULL;
    }

    /* Map buffer into CPU virtual address space */
    virt = xclMapBO(s_xrt_dev, bo, /*write=*/1);
    if (!virt || virt == (void *)(uintptr_t)(-1)) {
        fprintf(stderr, "inference: xclMapBO failed\n");
        xclFreeBO(s_xrt_dev, bo);
        free(buf);
        return NULL;
    }

    /* Retrieve physical (device) address from BO properties */
    memset(&props, 0, sizeof(props));
    if (xclGetBOProperties(s_xrt_dev, bo, &props) != 0) {
        fprintf(stderr, "inference: xclGetBOProperties failed\n");
        xclUnmapBO(s_xrt_dev, bo, virt);
        xclFreeBO(s_xrt_dev, bo);
        free(buf);
        return NULL;
    }

    buf->virt  = virt;
    buf->phys  = props.paddr;
    buf->count = n_elem;
    buf->bo    = (unsigned)bo;
    return buf;
}

void inference_buf_free(inference_buf_t *buf)
{
    if (buf) {
        xclUnmapBO(s_xrt_dev, (xclBufferHandle)buf->bo, buf->virt);
        xclFreeBO(s_xrt_dev, (xclBufferHandle)buf->bo);
        free(buf);
    }
}

/* Flush: write dirty CPU cache lines to DDR before the AXI master reads. */
void inference_buf_sync_to_device(inference_buf_t *buf)
{
    xclSyncBO(s_xrt_dev, (xclBufferHandle)buf->bo,
              XCL_BO_SYNC_BO_TO_DEVICE,
              buf->count * INFERENCE_BYTES_PER_ELEM, 0);
}

/* Invalidate: drop CPU cache lines after the AXI master has written. */
void inference_buf_sync_from_device(inference_buf_t *buf)
{
    xclSyncBO(s_xrt_dev, (xclBufferHandle)buf->bo,
              XCL_BO_SYNC_BO_FROM_DEVICE,
              buf->count * INFERENCE_BYTES_PER_ELEM, 0);
}

#else  /* bare-metal */

////////////////////////////////////////////////////////////////////////
/* Bare-metal — heap allocation (virtual address == physical address)  */
/*                                                                     */
/* On Xilinx standalone/FreeRTOS BSP the MMU uses a flat (identity)   */
/* mapping for DDR, so virtual and physical addresses are equal.       */
////////////////////////////////////////////////////////////////////////

#include "xil_cache.h"
#include "xil_types.h"

int  inference_buf_pool_init(void)   { return 0; }
void inference_buf_pool_deinit(void) {}

inference_buf_t *inference_buf_alloc(unsigned n_elem)
{
    size_t bytes = ((size_t)n_elem * INFERENCE_BYTES_PER_ELEM + 63u) & ~(size_t)63u;
    inference_buf_t *buf;
    void *mem;

    buf = (inference_buf_t *)malloc(sizeof(inference_buf_t));
    if (!buf) return NULL;

    mem = malloc(bytes);
    if (!mem) { free(buf); return NULL; }

    buf->virt  = mem;
    /* VA == PA on Xilinx standalone with identity-mapped DDR */
    buf->phys  = (uint64_t)(uintptr_t)mem;
    buf->count = n_elem;
    return buf;
}

void inference_buf_free(inference_buf_t *buf)
{
    if (buf) {
        free(buf->virt);
        free(buf);
    }
}

void inference_buf_sync_to_device(inference_buf_t *buf)
{
    Xil_DCacheFlushRange((INTPTR)buf->virt,
                         (INTPTR)(buf->count * INFERENCE_BYTES_PER_ELEM));
}

void inference_buf_sync_from_device(inference_buf_t *buf)
{
    Xil_DCacheInvalidateRange((INTPTR)buf->virt,
                              (INTPTR)(buf->count * INFERENCE_BYTES_PER_ELEM));
}

#endif /* __linux__ */
"""

# scripts/check_inference_setup.sh — preflight check for the inference library.
# {model_name} and {pool_bytes} are substituted by generate_setup_script().
_SETUP_SCRIPT_TEMPLATE = """\
#!/bin/sh
# check_inference_setup.sh — verify XRT prerequisites for the inference library
#
# Auto-generated by inference-scheduler
# Model   : {model_name}
# Required: {pool_bytes} bytes of DMA-capable memory
#
# The Linux inference library uses the XRT runtime (xclAllocBO / xclSyncBO)
# for DMA buffer allocation and cache coherency.
#
# Usage:
#   sh scripts/check_inference_setup.sh

POOL_BYTES={pool_bytes}
ERRORS=0

echo "Checking XRT inference library prerequisites..."
echo "  Required DMA pool : $POOL_BYTES bytes"

# -----------------------------------------------------------------------
# 1. Locate xrt.h
#    Try (in order):
#      a) pkg-config xrt               (preferred — works on Kria Ubuntu)
#      b) /usr/include/xrt/xrt.h       (Kria apt package layout)
#      c) $INFERENCE_XRT_DIR/include/xrt.h  (user override / cross-compile)
#      d) /opt/xilinx/xrt/include/xrt.h    (classic XRT install)
# -----------------------------------------------------------------------
XRT_HEADER=""

if pkg-config --exists xrt 2>/dev/null; then
    _inc=$(pkg-config --variable=includedir xrt 2>/dev/null)
    if [ -f "$_inc/xrt.h" ]; then
        XRT_HEADER="$_inc/xrt.h"
    elif [ -f "$_inc/xrt/xrt.h" ]; then
        XRT_HEADER="$_inc/xrt/xrt.h"
    fi
fi

if [ -z "$XRT_HEADER" ]; then
    for _candidate in \
        /usr/include/xrt/xrt.h \
        ${{INFERENCE_XRT_DIR:-/opt/xilinx/xrt}}/include/xrt.h \
        /opt/xilinx/xrt/include/xrt.h
    do
        if [ -f "$_candidate" ]; then
            XRT_HEADER="$_candidate"
            break
        fi
    done
fi

if [ -n "$XRT_HEADER" ]; then
    echo "  xrt.h             : $XRT_HEADER  OK"
else
    echo "ERROR: xrt.h not found. Install XRT:" >&2
    echo "         sudo apt install xrt  (Kria/Ubuntu)" >&2
    echo "       or set INFERENCE_XRT_DIR to your XRT prefix." >&2
    ERRORS=$((ERRORS + 1))
fi

# -----------------------------------------------------------------------
# 2. Locate libxrt_core.so
# -----------------------------------------------------------------------
XRT_LIB=""

if pkg-config --exists xrt 2>/dev/null; then
    _libdir=$(pkg-config --variable=libdir xrt 2>/dev/null)
    [ -f "$_libdir/libxrt_core.so" ] && XRT_LIB="$_libdir/libxrt_core.so"
fi

if [ -z "$XRT_LIB" ]; then
    for _candidate in \
        /usr/lib/libxrt_core.so \
        /usr/lib/aarch64-linux-gnu/libxrt_core.so \
        ${{INFERENCE_XRT_DIR:-/opt/xilinx/xrt}}/lib/libxrt_core.so \
        /opt/xilinx/xrt/lib/libxrt_core.so
    do
        if [ -f "$_candidate" ]; then
            XRT_LIB="$_candidate"
            break
        fi
    done
fi

if [ -n "$XRT_LIB" ]; then
    echo "  libxrt_core.so    : $XRT_LIB  OK"
else
    echo "ERROR: libxrt_core.so not found." >&2
    echo "       Install XRT or set INFERENCE_XRT_DIR." >&2
    ERRORS=$((ERRORS + 1))
fi

# -----------------------------------------------------------------------
# 3. XRT device node
# -----------------------------------------------------------------------
if ls /dev/dri/renderD* >/dev/null 2>&1; then
    echo "  DRI render node   : $(ls /dev/dri/renderD* | head -1)  OK"
else
    echo "WARNING: no /dev/dri/renderD* device found — is the XRT driver loaded?" >&2
fi

# -----------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------
if [ "$ERRORS" -eq 0 ]; then
    echo "XRT prerequisites OK"
else
    echo "$ERRORS prerequisite(s) missing — see errors above." >&2
    exit 1
fi
"""
