#!/usr/bin/env python3
"""
PYNQ hardware test for VectorOPKernel (ap_fixed<16,8>)

Mirrors the vadd_tb.sv stimulus / verification sequence:
  - Generator : create transaction (op, size, A fill, B fill, expected C)
  - Driver    : allocate CMA buffers, fill A/B, poison C, write registers, ap_start
  - Monitor   : poll ap_done, service ISR
  - Scoreboard: verify every C element equals the expected value

Register map: xvectoropkernel_hw.h (base 0xA000_0000)
  Verify REG_OP offset from the generated driver header after synthesis.
Data type   : ap_fixed<16,8>  — 1.0=0x0100, 2.0=0x0200, 3.0=0x0300

Usage (on KV260 PYNQ):
    sudo python3 test_pynq.py              # all operations, default size=256
    sudo python3 test_pynq.py --size 1024  # all operations, custom size
    sudo python3 test_pynq.py --no-load    # skip bitstream load
"""

import sys
import os
import time
import argparse
import numpy as np

try:
    from pynq import Overlay, MMIO, allocate
    PYNQ_AVAILABLE = True
except ImportError:
    PYNQ_AVAILABLE = False
    print("Warning: pynq not found — running in dry-run mode (no hardware access)")

# ---------------------------------------------------------------------------
# Board paths — edit to match deployment on your KV260
# ---------------------------------------------------------------------------
BITSTREAM_DEFAULT = "/home/xilinx/design_vadd/design_vadd.bit"
# Vivado project paths (for development/NFS access):
BITSTREAM_VIVADO  = ("/home/ivan/vivado_projects/axi_test/"
                     "axi_test.runs/impl_1/design_vadd.bit")
HWH_VIVADO        = ("/home/ivan/vivado_projects/axi_test/"
                     "axi_test.gen/sources_1/bd/design_vadd/"
                     "hw_handoff/design_vadd.hwh")

# ---------------------------------------------------------------------------
# ap_fixed<16,8> encoding
#   Signed 16-bit, 8 integer bits, 8 fractional bits.
#   Encoding : v (float) → round(v × 2^8) stored as int16
#   Decoding : raw (int16) → raw / 2^8 (float)
# ---------------------------------------------------------------------------
_FRAC  = 8
_SCALE = 1 << _FRAC  # 256

def to_fixed16(v: float) -> np.int16:
    return np.int16(int(round(v * _SCALE)))

def from_fixed16(raw: np.int16) -> float:
    return int(raw) / _SCALE

# Saturated extremes of ap_fixed<16,8>
SAT_MAX = to_fixed16(128.0 - 1.0 / 256.0)   # 0x7FFF =  127.99609375
SAT_MIN = to_fixed16(-128.0)                  # 0x8000 = -128.0

# Poison sentinel: unwritten C elements should never equal any valid result
C_POISON = np.int16(-8531)  # bit pattern 0xDEAD

# ---------------------------------------------------------------------------
# Operation codes — must match Op enum in VectorOP.h
# ---------------------------------------------------------------------------
OP_ADD   = 0
OP_SUB   = 1
OP_MUL   = 2
OP_DIV   = 3
OP_RELU  = 4
OP_RELU6 = 5

OP_NAMES = {
    OP_ADD:   "ADD",
    OP_SUB:   "SUB",
    OP_MUL:   "MUL",
    OP_DIV:   "DIV",
    OP_RELU:  "RELU",
    OP_RELU6: "RELU6",
}

# ---------------------------------------------------------------------------
# AXI-Lite register offsets
# Source: xvectoropkernel_hw.h (generated by Vitis HLS after synthesis).
# REG_OP: tentative 0x3C — confirm from the generated header after synthesis.
# ---------------------------------------------------------------------------
REG_AP_CTRL = 0x00  # bit0=ap_start, bit1=ap_done, bit2=ap_idle, bit3=ap_ready
REG_GIE     = 0x04  # bit0=global interrupt enable
REG_IER     = 0x08  # bit0=enable ap_done interrupt
REG_ISR     = 0x0C  # bit0=ap_done (TOW clear)
REG_A_LO    = 0x10  # a base address [31:0]
REG_A_HI    = 0x14  # a base address [63:32]
REG_B_LO    = 0x1C  # b base address [31:0]
REG_B_HI    = 0x20  # b base address [63:32]
REG_C_LO    = 0x28  # c base address [31:0]
REG_C_HI    = 0x2C  # c base address [63:32]
REG_SIZE    = 0x34  # vector length (elements)
REG_OP      = 0x3C  # operation selector (Op enum) — verify after synthesis

CTRL_BASE   = 0xA000_0000
CTRL_RANGE  = 0x44  # covers 0x00 – 0x40


# ---------------------------------------------------------------------------
# Reference model — matches saturate() + subkernel logic in VectorOP.cpp
# ---------------------------------------------------------------------------
_SAT_MIN_F = -128.0
_SAT_MAX_F =  128.0 - 1.0 / 256.0

def _sat(v: float) -> np.int16:
    return to_fixed16(max(_SAT_MIN_F, min(_SAT_MAX_F, v)))

def ref_result(op: int, a_f16: np.int16, b_f16: np.int16) -> np.int16:
    a = from_fixed16(a_f16)
    b = from_fixed16(b_f16)
    if   op == OP_ADD:   return _sat(a + b)
    elif op == OP_SUB:   return _sat(a - b)
    elif op == OP_MUL:   return _sat(a * b)
    elif op == OP_DIV:   return np.int16(0) if b == 0.0 else _sat(a / b)
    elif op == OP_RELU:  return to_fixed16(max(0.0, a))
    elif op == OP_RELU6: return to_fixed16(min(max(0.0, a), 6.0))
    else:                return a_f16


# ---------------------------------------------------------------------------
# VectorOPKernel — thin AXI-Lite wrapper
# Mirrors the driver and monitor classes from vadd_tb.sv.
# ---------------------------------------------------------------------------
class VectorOPKernel:
    def __init__(self, base: int = CTRL_BASE, addr_range: int = CTRL_RANGE):
        self._mmio = MMIO(base, addr_range)

    # ── Register helpers ──────────────────────────────────────────────────────

    def _wr(self, off: int, val: int) -> None:
        self._mmio.write(off, int(val) & 0xFFFF_FFFF)

    def _rd(self, off: int) -> int:
        return self._mmio.read(off)

    # ── Driver interface ───────────────────────────────────────────────────────

    def configure(self, phys_a: int, phys_b: int, phys_c: int,
                  size: int, op: int) -> None:
        """Write base addresses, size, and operation — mirrors driver sequence."""
        self._wr(REG_A_LO,  phys_a & 0xFFFF_FFFF)
        self._wr(REG_A_HI, (phys_a >> 32) & 0xFFFF_FFFF)
        self._wr(REG_B_LO,  phys_b & 0xFFFF_FFFF)
        self._wr(REG_B_HI, (phys_b >> 32) & 0xFFFF_FFFF)
        self._wr(REG_C_LO,  phys_c & 0xFFFF_FFFF)
        self._wr(REG_C_HI, (phys_c >> 32) & 0xFFFF_FFFF)
        self._wr(REG_SIZE,  size)
        self._wr(REG_OP,    op)

    def enable_interrupt(self) -> None:
        self._wr(REG_GIE, 1)
        self._wr(REG_IER, 1)

    def start(self) -> None:
        self._wr(REG_AP_CTRL, 0x1)

    # ── Monitor interface ──────────────────────────────────────────────────────

    def wait_done(self, timeout_s: float = 5.0) -> bool:
        """Poll ap_ctrl[1] (ap_done) until set or timeout expires."""
        deadline = time.monotonic() + timeout_s
        while time.monotonic() < deadline:
            if self._rd(REG_AP_CTRL) & 0x2:
                return True
            time.sleep(1e-5)  # 10 µs poll interval
        return False

    def service_isr(self) -> int:
        """Read and TOW-clear ISR, disable GIE — mirrors monitor service sequence."""
        isr = self._rd(REG_ISR)
        self._wr(REG_ISR, isr)   # Toggle-On-Write: write set bits to clear
        self._wr(REG_GIE, 0)
        return isr

    def ap_ctrl_str(self) -> str:
        v = self._rd(REG_AP_CTRL)
        return (f"ap_ctrl=0x{v:08x}  "
                f"start={v & 1} done={(v >> 1) & 1} "
                f"idle={(v >> 2) & 1} ready={(v >> 3) & 1}")


# ---------------------------------------------------------------------------
# run_test — mirrors generator → driver → monitor → scoreboard flow
# ---------------------------------------------------------------------------
def run_test(kernel: VectorOPKernel, op: int, a_fill: np.int16,
             b_fill: np.int16, size: int, verbose: bool = True) -> bool:
    """
    Run one VectorOP test and return True on PASS.

    For unary ops (OP_RELU, OP_RELU6) the b buffer is not allocated: the
    kernel issues no AXI transactions on gmem1 for those operations, so
    b_addr in the register map is written as 0 and ignored by the hardware.

    C is pre-poisoned with 0xDEAD; every element is verified against the
    reference model after the kernel completes.
    """
    is_unary  = op in (OP_RELU, OP_RELU6)
    c_expect  = ref_result(op, a_fill, b_fill)

    buf_a = allocate(shape=(size,), dtype=np.int16)
    buf_b = None if is_unary else allocate(shape=(size,), dtype=np.int16)
    buf_c = allocate(shape=(size,), dtype=np.int16)

    try:
        phys_a = buf_a.physical_address
        phys_b = 0 if is_unary else buf_b.physical_address
        phys_c = buf_c.physical_address

        # ── Driver: fill A (and B for binary ops), poison C ───────────────────
        buf_a[:] = a_fill
        buf_a.flush()
        if buf_b is not None:
            buf_b[:] = b_fill
            buf_b.flush()
        buf_c[:] = C_POISON
        buf_c.flush()

        if verbose:
            b_str = "(unused)" if is_unary else \
                    f"{from_fixed16(b_fill):.4f} (0x{int(b_fill)&0xFFFF:04x})"
            print(f"  A={from_fixed16(a_fill):.4f} (0x{int(a_fill)&0xFFFF:04x})"
                  f"  B={b_str}"
                  f"  expect C={from_fixed16(c_expect):.4f}"
                  f" (0x{int(c_expect)&0xFFFF:04x})"
                  f"  size={size}")

        # ── Driver: program registers and assert ap_start ─────────────────────
        kernel.configure(phys_a, phys_b, phys_c, size, op)
        kernel.enable_interrupt()
        kernel.start()

        # ── Monitor: wait for ap_done ─────────────────────────────────────────
        t0 = time.monotonic()
        done = kernel.wait_done(timeout_s=5.0)
        elapsed_us = (time.monotonic() - t0) * 1e6

        if not done:
            print(f"  [TIMEOUT] ap_done not seen within 5 s")
            return False

        isr = kernel.service_isr()

        if verbose:
            print(f"  {kernel.ap_ctrl_str()}"
                  f"  ISR=0x{isr:08x}  elapsed={elapsed_us:.1f} µs")

        # ── Scoreboard: invalidate cache, verify C ────────────────────────────
        buf_c.invalidate()

        errors = 0
        for i, elem in enumerate(buf_c):
            if elem != c_expect:
                if errors < 10:
                    print(f"  MISMATCH C[{i}]: "
                          f"got 0x{int(elem)&0xFFFF:04x} ({from_fixed16(elem):.4f})  "
                          f"expected 0x{int(c_expect)&0xFFFF:04x}"
                          f" ({from_fixed16(c_expect):.4f})")
                errors += 1
        if errors > 10:
            print(f"  ... ({errors - 10} more mismatches suppressed)")

        return errors == 0

    finally:
        buf_a.freebuffer()
        if buf_b is not None:
            buf_b.freebuffer()
        buf_c.freebuffer()


# ---------------------------------------------------------------------------
# Dry-run stub (when pynq is not importable)
# ---------------------------------------------------------------------------
def run_test_dryrun(op: int, a_fill: np.int16, b_fill: np.int16,
                    size: int, verbose: bool = True) -> bool:
    """Software model — no hardware required."""
    is_unary = op in (OP_RELU, OP_RELU6)
    a = np.full(size, a_fill, dtype=np.int16)
    b = np.full(size, b_fill, dtype=np.int16)  # ignored for unary ops
    c = np.array([ref_result(op, av, bv) for av, bv in zip(a, b)], dtype=np.int16)
    c_expect = ref_result(op, a_fill, b_fill)
    b_str = "(unused)" if is_unary else f"0x{int(b_fill)&0xFFFF:04x}"
    if verbose:
        print(f"  [dry-run] op={OP_NAMES[op]}  size={size}"
              f"  a=0x{int(a_fill)&0xFFFF:04x}  b={b_str}"
              f"  c[0]=0x{int(c[0])&0xFFFF:04x}")
    errors = int(np.sum(c != c_expect))
    return errors == 0


# ---------------------------------------------------------------------------
# Test matrix
#
# Each row: (op, a_fill, b_fill, description)
# a_fill / b_fill are ap_fixed<16,8> encoded as int16.
#
# Saturation tests are included for ADD and MUL to verify that the kernel
# clamps to 0x7FFF / 0x8000 rather than wrapping.
# ---------------------------------------------------------------------------
def build_test_matrix():
    return [
        # Normal range
        (OP_ADD,   to_fixed16( 1.0),  to_fixed16( 2.0),  "1.0 + 2.0 = 3.0"),
        (OP_SUB,   to_fixed16( 3.0),  to_fixed16( 1.0),  "3.0 - 1.0 = 2.0"),
        (OP_MUL,   to_fixed16( 2.0),  to_fixed16( 3.0),  "2.0 × 3.0 = 6.0"),
        (OP_DIV,   to_fixed16( 6.0),  to_fixed16( 3.0),  "6.0 ÷ 3.0 = 2.0"),
        # Saturation: result exceeds ap_fixed<16,8> max (127.99609375)
        (OP_ADD,   to_fixed16(100.0), to_fixed16(100.0), "100+100 → sat max"),
        (OP_MUL,   to_fixed16( 16.0), to_fixed16( 16.0), "16×16   → sat max"),
        # Saturation: result below ap_fixed<16,8> min (-128.0)
        (OP_SUB,   to_fixed16(-80.0), to_fixed16( 80.0), "-80-80  → sat min"),
        # ReLU: clamp negative to zero
        (OP_RELU,  to_fixed16(-2.0),  to_fixed16(  0.0), "relu(-2) = 0"),
        # ReLU: pass positive through unchanged
        (OP_RELU,  to_fixed16( 3.5),  to_fixed16(  0.0), "relu(3.5) = 3.5"),
        # ReLU6: clamp above 6 to 6
        (OP_RELU6, to_fixed16( 8.0),  to_fixed16(  0.0), "relu6(8)  = 6"),
        # ReLU6: clamp below 0 to 0
        (OP_RELU6, to_fixed16(-1.0),  to_fixed16(  0.0), "relu6(-1) = 0"),
        # ReLU6: pass value in [0,6] unchanged
        (OP_RELU6, to_fixed16( 4.0),  to_fixed16(  0.0), "relu6(4)  = 4"),
    ]


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(
        description="PYNQ hardware test for VectorOPKernel (ap_fixed<16,8>)")
    parser.add_argument("--size", type=int, default=256,
                        help="vector size for all tests (default: 256)")
    parser.add_argument("--bitstream", default=BITSTREAM_DEFAULT,
                        help="path to .bit file (must have matching .hwh alongside)")
    parser.add_argument("--no-load", action="store_true",
                        help="skip bitstream loading (assume already programmed)")
    parser.add_argument("--quiet", action="store_false", dest="verbose",
                        help="suppress per-test register / address output")
    args = parser.parse_args()

    test_matrix = build_test_matrix()

    print("=" * 62)
    print(" VectorOP PYNQ Hardware Test")
    print(f" Data type: ap_fixed<16,8>   AXI-Lite base: 0x{CTRL_BASE:08x}")
    print(f" Operations: ADD SUB MUL DIV RELU RELU6   size={args.size}")
    print("=" * 62)

    # ── Load bitstream ─────────────────────────────────────────────────────
    if PYNQ_AVAILABLE and not args.no_load:
        bitstream = args.bitstream
        if not os.path.exists(bitstream) and os.path.exists(BITSTREAM_VIVADO):
            bitstream = BITSTREAM_VIVADO
            print(f"Note: using Vivado project bitstream:\n  {bitstream}")

        if os.path.exists(bitstream):
            hwh_alongside = os.path.splitext(bitstream)[0] + ".hwh"
            if not os.path.exists(hwh_alongside) and os.path.exists(HWH_VIVADO):
                import shutil
                shutil.copy(HWH_VIVADO, hwh_alongside)
                print(f"Copied .hwh → {hwh_alongside}")
            print(f"Loading overlay: {bitstream}")
            _ol = Overlay(bitstream)
            print("Overlay loaded.\n")
        else:
            print(f"Warning: bitstream not found at {bitstream}")
            print("Assuming device is already programmed.\n")
    elif not PYNQ_AVAILABLE:
        print("Running in dry-run mode (no hardware).\n")

    # ── Run tests ──────────────────────────────────────────────────────────
    if PYNQ_AVAILABLE:
        kernel = VectorOPKernel()

    passed = 0
    failed = 0
    n = len(test_matrix)

    for idx, (op, a_fill, b_fill, desc) in enumerate(test_matrix):
        label = f"[{idx+1}/{n}] {OP_NAMES[op]:<5}  {desc}"
        print(label)

        if PYNQ_AVAILABLE:
            ok = run_test(kernel, op, a_fill, b_fill, args.size,
                          verbose=args.verbose)
        else:
            ok = run_test_dryrun(op, a_fill, b_fill, args.size,
                                 verbose=args.verbose)

        c_exp = ref_result(op, a_fill, b_fill)
        if ok:
            print(f"  PASS  — all {args.size} C elements ="
                  f" 0x{int(c_exp)&0xFFFF:04x} ({from_fixed16(c_exp):.5f})")
            passed += 1
        else:
            print(f"  FAIL")
            failed += 1

    # ── Summary ────────────────────────────────────────────────────────────
    print()
    print("=" * 62)
    if failed == 0:
        print(f" All {passed} tests PASSED.")
    else:
        print(f" {passed} passed, {failed} FAILED.")
    print("=" * 62)

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
