# Vitis HLS synthesis script for MatmulKernel — generated by CMake.
# Runs C synthesis and exports the result as a Vivado IP catalog archive.
#
# Variables substituted by CMake configure_file (@ONLY):
#   MM_HLS_PROJECT_NAME      — HLS project directory name
#   MM_BOARD_OPTION          — set_part command (includes -board if present)
#   MM_SRC_SYNTHESIS         — space-separated kernel source file paths
#   MM_SYNTHESIS_FLAGS       — -O3 plus -I paths for include directories
#   MM_TARGET_CLOCK_TCL      — target clock frequency in MHz
#   MM_IP_OUTPUT_DIR         — output directory for the exported IP catalog

open_project matmul_kv260
open_solution solution1 -flow_target vivado

set_part {xck26-sfvc784-2LV-c} -board {xilinx.com:kv260_som:part0:1.4}

add_files -cflags "-O3 -I/home/ivan/projects/axi_demo/kernels/matmul/include -I/home/ivan/projects/axi_demo/kernels/matmul/kv260" "/home/ivan/projects/axi_demo/kernels/matmul/kernel/MatmulKernel.cpp"
set_top MatmulKernel

create_clock -period 300MHz -name default

# 64-bit AXI addresses for systems with >4 GB address space (e.g. KV260 PS DDR).
config_interface -m_axi_addr64
# Set m_axi bus width (controlled by CMake AXI_BUS_WIDTH).
config_interface -m_axi_max_widen_bitwidth 32
config_rtl -reset_level low

csynth_design
export_design -format ip_catalog -output /home/ivan/projects/axi_demo/kernels/matmul/kv260/ip_catalog

exit
