"""Tests for models that use all three kernels: VectorOPKernel, MatmulKernel, ConvKernel.

Models generated by test/gen_mixed_all_kernels_models.py:
  1  mixed_all_relu_conv_matmul      Relu → Conv → Relu → MatMul
  2  mixed_all_conv_matmul_relu      Conv(+bias) → Relu → MatMul → Relu
  3  mixed_all_norm_conv_project     Sub → Mul → Conv → Relu → MatMul
  4  mixed_all_matmul_relu_conv      MatMul → Relu → Conv → Relu6
  5  mixed_all_skip_conv_matmul      Conv → Relu → Add(skip) → MatMul
  6  mixed_all_two_conv_matmul_relu6 Conv(+bias) → Relu → Conv → Relu → MatMul → Relu6
  7  mixed_all_sub_matmul_conv       Sub → MatMul → Relu → Conv → Relu6
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.graph   import OnnxGraph
from src.codegen import CodeGenerator
from src.nodes   import ConvNode, MatmulNode, ScheduledNode
from src.kernels import KERNEL_REGISTRY


_MODELS_DIR = os.path.join(os.path.dirname(__file__), "models")
_SENTINEL   = "mixed_all_relu_conv_matmul.onnx"


def _all_models_exist() -> bool:
    return os.path.isfile(os.path.join(_MODELS_DIR, _SENTINEL))


def _path(name: str) -> str:
    return os.path.join(_MODELS_DIR, name)


def _gen(name: str) -> CodeGenerator:
    p = _path(name)
    return CodeGenerator(OnnxGraph(p), model_path=p)


# ---------------------------------------------------------------------------
# ConvKernel registry sanity check (no model dependency)
# ---------------------------------------------------------------------------

class TestConvKernelRegistry(unittest.TestCase):
    """Verify ConvKernel is present in KERNEL_REGISTRY with correct metadata."""

    def test_conv_entry_exists(self):
        self.assertIn("ConvKernel", KERNEL_REGISTRY)

    def test_driver_prefix(self):
        self.assertEqual(KERNEL_REGISTRY["ConvKernel"].driver_prefix, "xconvkernel")

    def test_c_type(self):
        self.assertEqual(KERNEL_REGISTRY["ConvKernel"].c_type, "XConvkernel")

    def test_uio_default(self):
        self.assertEqual(KERNEL_REGISTRY["ConvKernel"].uio_default, "ConvKernel_0")

    def test_axi_base(self):
        self.assertEqual(KERNEL_REGISTRY["ConvKernel"].axi_base, 0xA002_0000)

    def test_c_var(self):
        self.assertEqual(KERNEL_REGISTRY["ConvKernel"].c_var, "s_convkernel")

    def test_init_param(self):
        self.assertEqual(KERNEL_REGISTRY["ConvKernel"].init_param, "convkernel_instance")

    def test_instance_macro(self):
        self.assertEqual(
            KERNEL_REGISTRY["ConvKernel"].instance_macro,
            "INFERENCE_CONVKERNEL_INSTANCE",
        )

    def test_driver_files_present(self):
        files = KERNEL_REGISTRY["ConvKernel"].driver_files
        for f in ("xconvkernel.h", "xconvkernel_hw.h",
                  "xconvkernel.c", "xconvkernel_sinit.c", "xconvkernel_linux.c"):
            self.assertIn(f, files)

    def test_registry_order_vop_mm_conv(self):
        """VectorOPKernel precedes MatmulKernel precedes ConvKernel in registry."""
        names = list(KERNEL_REGISTRY.keys())
        self.assertLess(names.index("VectorOPKernel"), names.index("MatmulKernel"))
        self.assertLess(names.index("MatmulKernel"),   names.index("ConvKernel"))


# ---------------------------------------------------------------------------
# Active kernels — all three must be present in every model
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsActive(unittest.TestCase):
    """_active_kernels must include VectorOPKernel, MatmulKernel, ConvKernel."""

    _MODELS = [
        "mixed_all_relu_conv_matmul.onnx",
        "mixed_all_conv_matmul_relu.onnx",
        "mixed_all_norm_conv_project.onnx",
        "mixed_all_matmul_relu_conv.onnx",
        "mixed_all_skip_conv_matmul.onnx",
        "mixed_all_two_conv_matmul_relu6.onnx",
        "mixed_all_sub_matmul_conv.onnx",
    ]

    def _kernel_names(self, model: str):
        return [kd.name for kd in _gen(model)._active_kernels]

    def test_all_three_kernels_relu_conv_matmul(self):
        names = self._kernel_names("mixed_all_relu_conv_matmul.onnx")
        for k in ("VectorOPKernel", "MatmulKernel", "ConvKernel"):
            self.assertIn(k, names)

    def test_all_three_kernels_conv_matmul_relu(self):
        names = self._kernel_names("mixed_all_conv_matmul_relu.onnx")
        for k in ("VectorOPKernel", "MatmulKernel", "ConvKernel"):
            self.assertIn(k, names)

    def test_all_three_kernels_norm_conv_project(self):
        names = self._kernel_names("mixed_all_norm_conv_project.onnx")
        for k in ("VectorOPKernel", "MatmulKernel", "ConvKernel"):
            self.assertIn(k, names)

    def test_all_three_kernels_matmul_relu_conv(self):
        names = self._kernel_names("mixed_all_matmul_relu_conv.onnx")
        for k in ("VectorOPKernel", "MatmulKernel", "ConvKernel"):
            self.assertIn(k, names)

    def test_all_three_kernels_skip_conv_matmul(self):
        names = self._kernel_names("mixed_all_skip_conv_matmul.onnx")
        for k in ("VectorOPKernel", "MatmulKernel", "ConvKernel"):
            self.assertIn(k, names)

    def test_all_three_kernels_two_conv_relu6(self):
        names = self._kernel_names("mixed_all_two_conv_matmul_relu6.onnx")
        for k in ("VectorOPKernel", "MatmulKernel", "ConvKernel"):
            self.assertIn(k, names)

    def test_all_three_kernels_sub_matmul_conv(self):
        names = self._kernel_names("mixed_all_sub_matmul_conv.onnx")
        for k in ("VectorOPKernel", "MatmulKernel", "ConvKernel"):
            self.assertIn(k, names)

    def test_kernel_order_vop_before_mm_before_conv(self):
        """Registry insertion order: VectorOP < MatMul < Conv in _active_kernels."""
        names = self._kernel_names("mixed_all_relu_conv_matmul.onnx")
        self.assertLess(names.index("VectorOPKernel"), names.index("MatmulKernel"))
        self.assertLess(names.index("MatmulKernel"),   names.index("ConvKernel"))


# ---------------------------------------------------------------------------
# Generated source — all three helpers and call sites in every model
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsSource(unittest.TestCase):
    """inference.c contains the correct helper functions and call sites."""

    def _src(self, name: str) -> str:
        return _gen(name).generate_source()

    # ---- helper function declarations ---- #

    def test_run_conv_helper_declared(self):
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("static void run_conv(", s)

    def test_run_matmul_helper_declared(self):
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("static void run_matmul(", s)

    def test_run_op_helper_declared(self):
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("static void run_op(", s)

    # ---- all three static kernel instances ---- #

    def test_three_static_instances(self):
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("XVectoropkernel s_vectoropkernel", s)
        self.assertIn("XMatmulkernel s_matmulkernel",     s)
        self.assertIn("XConvkernel s_convkernel",         s)

    def test_all_three_headers_included(self):
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn('#include "xvectoropkernel.h"', s)
        self.assertIn('#include "xmatmulkernel.h"',   s)
        self.assertIn('#include "xconvkernel.h"',     s)

    # ---- call counts in inference_run body ---- #

    def _body(self, name: str) -> str:
        s = self._src(name)
        return s[s.find("void inference_run("):]

    def test_relu_conv_matmul_call_counts(self):
        b = self._body("mixed_all_relu_conv_matmul.onnx")
        self.assertEqual(b.count("run_conv("), 1)
        self.assertEqual(b.count("run_matmul("), 1)
        self.assertEqual(b.count("run_op("), 2)

    def test_conv_matmul_relu_call_counts(self):
        b = self._body("mixed_all_conv_matmul_relu.onnx")
        self.assertEqual(b.count("run_conv("), 1)
        self.assertEqual(b.count("run_matmul("), 1)
        self.assertEqual(b.count("run_op("), 2)

    def test_norm_conv_project_call_counts(self):
        b = self._body("mixed_all_norm_conv_project.onnx")
        self.assertEqual(b.count("run_conv("), 1)
        self.assertEqual(b.count("run_matmul("), 1)
        self.assertEqual(b.count("run_op("), 3)

    def test_matmul_relu_conv_call_counts(self):
        b = self._body("mixed_all_matmul_relu_conv.onnx")
        self.assertEqual(b.count("run_conv("), 1)
        self.assertEqual(b.count("run_matmul("), 1)
        self.assertEqual(b.count("run_op("), 2)

    def test_skip_conv_matmul_call_counts(self):
        b = self._body("mixed_all_skip_conv_matmul.onnx")
        self.assertEqual(b.count("run_conv("), 1)
        self.assertEqual(b.count("run_matmul("), 1)
        self.assertEqual(b.count("run_op("), 2)

    def test_two_conv_matmul_relu6_call_counts(self):
        b = self._body("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertEqual(b.count("run_conv("), 2)
        self.assertEqual(b.count("run_matmul("), 1)
        self.assertEqual(b.count("run_op("), 3)

    def test_sub_matmul_conv_call_counts(self):
        b = self._body("mixed_all_sub_matmul_conv.onnx")
        self.assertEqual(b.count("run_conv("), 1)
        self.assertEqual(b.count("run_matmul("), 1)
        self.assertEqual(b.count("run_op("), 3)

    # ---- call-site ordering ---- #

    def test_relu_conv_matmul_order(self):
        """Relu → Conv → Relu → MatMul."""
        b = self._body("mixed_all_relu_conv_matmul.onnx")
        relu_pos  = b.find("VECTOROP_RELU")
        conv_pos  = b.find("run_conv(")
        matmul_pos = b.find("run_matmul(")
        self.assertLess(relu_pos,   conv_pos)
        self.assertLess(conv_pos,   matmul_pos)

    def test_conv_matmul_relu_order(self):
        """Conv → Relu → MatMul → Relu."""
        b = self._body("mixed_all_conv_matmul_relu.onnx")
        conv_pos   = b.find("run_conv(")
        relu_pos   = b.find("VECTOROP_RELU")
        matmul_pos = b.find("run_matmul(")
        # second relu is after matmul
        second_relu = b.find("VECTOROP_RELU", relu_pos + 1)
        self.assertLess(conv_pos,   relu_pos)
        self.assertLess(relu_pos,   matmul_pos)
        self.assertLess(matmul_pos, second_relu)

    def test_matmul_relu_conv_order(self):
        """MatMul → Relu → Conv → Relu6."""
        b = self._body("mixed_all_matmul_relu_conv.onnx")
        matmul_pos = b.find("run_matmul(")
        relu_pos   = b.find("VECTOROP_RELU")
        conv_pos   = b.find("run_conv(")
        relu6_pos  = b.find("VECTOROP_RELU6")
        self.assertLess(matmul_pos, relu_pos)
        self.assertLess(relu_pos,   conv_pos)
        self.assertLess(conv_pos,   relu6_pos)

    def test_skip_conv_matmul_order(self):
        """Conv → Relu → Add → MatMul."""
        b = self._body("mixed_all_skip_conv_matmul.onnx")
        conv_pos   = b.find("run_conv(")
        relu_pos   = b.find("VECTOROP_RELU")
        add_pos    = b.find("VECTOROP_ADD")
        matmul_pos = b.find("run_matmul(")
        self.assertLess(conv_pos,   relu_pos)
        self.assertLess(relu_pos,   add_pos)
        self.assertLess(add_pos,    matmul_pos)

    def test_sub_matmul_conv_order(self):
        """Sub → MatMul → Relu → Conv → Relu6."""
        b = self._body("mixed_all_sub_matmul_conv.onnx")
        sub_pos    = b.find("VECTOROP_SUB")
        matmul_pos = b.find("run_matmul(")
        relu_pos   = b.find("VECTOROP_RELU")
        conv_pos   = b.find("run_conv(")
        relu6_pos  = b.find("VECTOROP_RELU6")
        self.assertLess(sub_pos,    matmul_pos)
        self.assertLess(matmul_pos, relu_pos)
        self.assertLess(relu_pos,   conv_pos)
        self.assertLess(conv_pos,   relu6_pos)

    # ---- Conv bias argument ---- #

    def test_conv_without_bias_passes_null(self):
        """Conv without bias: third arg is NULL."""
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("run_conv(Z, Wc, NULL, A,", s)

    def test_conv_with_bias_passes_bias_tensor(self):
        """Conv with bias: third arg is the bias C name."""
        s = self._src("mixed_all_conv_matmul_relu.onnx")
        self.assertIn("run_conv(X, Wc, Bc, Z,", s)

    def test_two_conv_first_has_bias_second_null(self):
        s = self._src("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertIn("run_conv(X, Wc1, Bc1, Z1,", s)
        self.assertIn("run_conv(A1, Wc2, NULL, Z2,", s)

    # ---- skip connection ---- #

    def test_skip_connection_add_uses_x_and_a(self):
        """Add(X, A) → B uses both original input and conv output."""
        s = self._src("mixed_all_skip_conv_matmul.onnx")
        self.assertIn("run_op(X, A, B, 128u, VECTOROP_ADD, 1u, 0u, 0u);", s)

    # ---- norm (Sub + Mul) ---- #

    def test_norm_sub_call(self):
        s = self._src("mixed_all_norm_conv_project.onnx")
        self.assertIn("run_op(X, offset, Z1, 256u, VECTOROP_SUB, 1u, 0u, 0u);", s)

    def test_norm_mul_call(self):
        s = self._src("mixed_all_norm_conv_project.onnx")
        self.assertIn("run_op(Z1, scale, Z2, 256u, VECTOROP_MUL, 1u, 0u, 0u);", s)

    # ---- Relu6 path ---- #

    def test_matmul_relu_conv_final_relu6(self):
        s = self._src("mixed_all_matmul_relu_conv.onnx")
        self.assertIn("run_op(B, NULL, Y, 512u, VECTOROP_RELU6, 1u, 0u, 0u);", s)

    def test_two_conv_final_relu6(self):
        s = self._src("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertIn("run_op(B, NULL, Y, 256u, VECTOROP_RELU6, 1u, 0u, 0u);", s)

    def test_sub_matmul_conv_final_relu6(self):
        s = self._src("mixed_all_sub_matmul_conv.onnx")
        self.assertIn("run_op(B, NULL, Y, 256u, VECTOROP_RELU6, 1u, 0u, 0u);", s)


# ---------------------------------------------------------------------------
# run_conv call geometry parameters
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsConvParams(unittest.TestCase):
    """Verify run_conv() is emitted with the correct geometry arguments."""

    def _src(self, name: str) -> str:
        return _gen(name).generate_source()

    def test_relu_conv_matmul_conv_dims(self):
        """Conv: batch=1, IC=4, IH=8, IW=8, OC=8, OH=8, OW=8, k=1x1, s=1x1, p=0,0."""
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("1u, 4u, 8u, 8u,", s)
        self.assertIn("8u, 8u, 8u,", s)
        self.assertIn("1u, 1u, 1u, 1u,", s)   # kh, kw, sh, sw

    def test_conv_matmul_relu_conv_dims(self):
        """Conv: batch=1, IC=3, IH=8, IW=8, OC=8, OH=8, OW=8, k=3x3, p=1,1."""
        s = self._src("mixed_all_conv_matmul_relu.onnx")
        self.assertIn("1u, 3u, 8u, 8u,", s)
        self.assertIn("3u, 3u, 1u, 1u,", s)   # kh, kw, sh, sw

    def test_norm_conv_project_conv_dims(self):
        """Conv: batch=1, IC=4, IH=8, IW=8, OC=8, OH=8, OW=8, k=3x3, p=1,1."""
        s = self._src("mixed_all_norm_conv_project.onnx")
        self.assertIn("1u, 4u, 8u, 8u,", s)
        self.assertIn("3u, 3u, 1u, 1u,", s)

    def test_matmul_relu_conv_conv_dims(self):
        """Conv: batch=1, IC=4, IH=8, IW=8, OC=8, OH=8, OW=8, k=1x1, s=1x1, p=0,0."""
        s = self._src("mixed_all_matmul_relu_conv.onnx")
        self.assertIn("1u, 4u, 8u, 8u,", s)
        self.assertIn("1u, 1u, 1u, 1u,", s)

    def test_skip_conv_matmul_conv_dims(self):
        """Conv: batch=1, IC=8, IH=4, IW=4, OC=8, OH=4, OW=4, k=1x1, p=0,0."""
        s = self._src("mixed_all_skip_conv_matmul.onnx")
        self.assertIn("1u, 8u, 4u, 4u,", s)
        self.assertIn("8u, 4u, 4u,", s)        # OC, OH, OW

    def test_two_conv_matmul_relu6_first_conv_dims(self):
        """First Conv: batch=1, IC=3, IH=8, IW=8, OC=8, OH=8, OW=8, k=3x3, p=1,1."""
        s = self._src("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertIn("1u, 3u, 8u, 8u,", s)

    def test_two_conv_matmul_relu6_second_conv_dims(self):
        """Second Conv: batch=1, IC=8, IH=8, IW=8, OC=8, OH=8, OW=8, k=1x1, p=0,0."""
        s = self._src("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertIn("1u, 8u, 8u, 8u,", s)

    def test_sub_matmul_conv_conv_dims(self):
        """Conv: batch=1, IC=4, IH=4, IW=8, OC=8, OH=4, OW=8, k=1x1, p=0,0."""
        s = self._src("mixed_all_sub_matmul_conv.onnx")
        self.assertIn("1u, 4u, 4u, 8u,", s)
        self.assertIn("8u, 4u, 8u,", s)        # OC, OH, OW

    def test_conv_with_bias_flag_one(self):
        """Conv with bias: has_bias=1u, is_depthwise=0u → call ends with '1u, 0u);'."""
        s = self._src("mixed_all_conv_matmul_relu.onnx")
        self.assertIn("1u, 0u);", s)

    def test_conv_without_bias_flag_zero(self):
        """Conv without bias: has_bias=0u."""
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("0u);", s)


# ---------------------------------------------------------------------------
# run_matmul call dimensions
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsMatmulParams(unittest.TestCase):
    """Verify run_matmul() is emitted with the correct n, k, m, batch, strides."""

    def _src(self, name: str) -> str:
        return _gen(name).generate_source()

    def test_relu_conv_matmul_dims(self):
        """B[1,8,8,8] @ Wm[8,4]: batch=8, n=8, k=8, m=4, a_stride=64, c_stride=32."""
        s = self._src("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("8u, 8u, 4u, 8u,", s)
        self.assertIn("64u, 0u, 32u", s)

    def test_conv_matmul_relu_dims(self):
        """A[1,8,8,8] @ Wm[8,4]: batch=8, n=8, k=8, m=4, a_stride=64, c_stride=32."""
        s = self._src("mixed_all_conv_matmul_relu.onnx")
        self.assertIn("8u, 8u, 4u, 8u,", s)
        self.assertIn("64u, 0u, 32u", s)

    def test_norm_conv_project_dims(self):
        """B[1,8,8,8] @ Wm[8,4]: batch=8, n=8, k=8, m=4, a_stride=64, c_stride=32."""
        s = self._src("mixed_all_norm_conv_project.onnx")
        self.assertIn("8u, 8u, 4u, 8u,", s)
        self.assertIn("64u, 0u, 32u", s)

    def test_matmul_relu_conv_dims(self):
        """X[1,4,8,8] @ Wm[8,8]: batch=4, n=8, k=8, m=8, a_stride=64, c_stride=64."""
        s = self._src("mixed_all_matmul_relu_conv.onnx")
        self.assertIn("8u, 8u, 8u, 4u,", s)
        self.assertIn("64u, 0u, 64u", s)

    def test_skip_conv_matmul_dims(self):
        """B[1,8,4,4] @ Wm[4,4]: batch=8, n=4, k=4, m=4, a_stride=16, c_stride=16."""
        s = self._src("mixed_all_skip_conv_matmul.onnx")
        self.assertIn("4u, 4u, 4u, 8u,", s)
        self.assertIn("16u, 0u, 16u", s)

    def test_two_conv_matmul_relu6_dims(self):
        """A2[1,8,8,8] @ Wm[8,4]: batch=8, n=8, k=8, m=4, a_stride=64, c_stride=32."""
        s = self._src("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertIn("8u, 8u, 4u, 8u,", s)
        self.assertIn("64u, 0u, 32u", s)

    def test_sub_matmul_conv_dims(self):
        """Z1[1,4,4,8] @ Wm[8,8]: batch=4, n=4, k=8, m=8, a_stride=32, c_stride=32."""
        s = self._src("mixed_all_sub_matmul_conv.onnx")
        self.assertIn("4u, 8u, 8u, 4u,", s)
        self.assertIn("32u, 0u, 32u", s)

    def test_all_matmul_calls_b_stride_zero(self):
        """Wm is 2-D in every model → b_batch_stride is always 0."""
        for name in [
            "mixed_all_relu_conv_matmul.onnx",
            "mixed_all_conv_matmul_relu.onnx",
            "mixed_all_norm_conv_project.onnx",
            "mixed_all_matmul_relu_conv.onnx",
            "mixed_all_skip_conv_matmul.onnx",
            "mixed_all_two_conv_matmul_relu6.onnx",
            "mixed_all_sub_matmul_conv.onnx",
        ]:
            with self.subTest(model=name):
                s = self._src(name)
                body = s[s.find("void inference_run("):]
                mm_idx = body.find("run_matmul(")
                semi   = body.find(");", mm_idx)
                call   = body[mm_idx:semi]
                self.assertIn("0u", call, f"b_stride should be 0 in {name}")


# ---------------------------------------------------------------------------
# Generated header — all three instance macros and init params
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsHeader(unittest.TestCase):
    """inference.h contains all three instance macros, init params, and AXI defaults."""

    def _hdr(self, name: str) -> str:
        return _gen(name).generate_header()

    def test_all_three_instance_macros(self):
        h = self._hdr("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("INFERENCE_VECTOROPKERNEL_INSTANCE", h)
        self.assertIn("INFERENCE_MATMULKERNEL_INSTANCE",   h)
        self.assertIn("INFERENCE_CONVKERNEL_INSTANCE",     h)

    def test_uio_defaults(self):
        h = self._hdr("mixed_all_relu_conv_matmul.onnx")
        self.assertIn('"VectorOPKernel_0"', h)
        self.assertIn('"MatmulKernel_0"',   h)
        self.assertIn('"ConvKernel_0"',     h)

    def test_init_signature_has_all_three_params(self):
        h = self._hdr("mixed_all_relu_conv_matmul.onnx")
        self.assertIn("vectoropkernel_instance", h)
        self.assertIn("matmulkernel_instance",   h)
        self.assertIn("convkernel_instance",     h)

    def test_no_broadcast_chunk_macros(self):
        """All intermediate tensors are flat (no broadcast VectorOP) — no CHUNK macros."""
        h = self._hdr("mixed_all_relu_conv_matmul.onnx")
        self.assertNotIn("_CHUNK_STRIDE", h)

    def test_two_conv_header_has_all_macros(self):
        h = self._hdr("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertIn("INFERENCE_VECTOROPKERNEL_INSTANCE", h)
        self.assertIn("INFERENCE_MATMULKERNEL_INSTANCE",   h)
        self.assertIn("INFERENCE_CONVKERNEL_INSTANCE",     h)

    def test_skip_model_no_chunk_macros(self):
        """Skip connection uses non-broadcast Add → no CHUNK macros."""
        h = self._hdr("mixed_all_skip_conv_matmul.onnx")
        self.assertNotIn("_CHUNK_STRIDE", h)


# ---------------------------------------------------------------------------
# Generated CMakeLists.txt — all three driver sets and AXI addresses
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsCMake(unittest.TestCase):
    """CMakeLists.txt lists all three driver file sets and AXI base addresses."""

    def _cmake(self, name: str) -> str:
        return _gen(name).generate_cmake()

    def _cm(self) -> str:
        return self._cmake("mixed_all_relu_conv_matmul.onnx")

    def test_all_three_driver_common_files(self):
        cm = self._cm()
        self.assertIn("xvectoropkernel.c", cm)
        self.assertIn("xmatmulkernel.c",   cm)
        self.assertIn("xconvkernel.c",     cm)

    def test_all_three_sinit_files(self):
        cm = self._cm()
        self.assertIn("xvectoropkernel_sinit.c", cm)
        self.assertIn("xmatmulkernel_sinit.c",   cm)
        self.assertIn("xconvkernel_sinit.c",     cm)

    def test_all_three_linux_files(self):
        cm = self._cm()
        self.assertIn("xvectoropkernel_linux.c", cm)
        self.assertIn("xmatmulkernel_linux.c",   cm)
        self.assertIn("xconvkernel_linux.c",     cm)

    def test_all_three_axi_addresses(self):
        cm = self._cm()
        self.assertIn("0xA0000000", cm)   # VectorOPKernel base
        self.assertIn("0xA0010000", cm)   # MatmulKernel base
        self.assertIn("0xA0020000", cm)   # ConvKernel base

    def test_two_conv_model_cmake(self):
        """Two-conv model also has all three driver sets."""
        cm = self._cmake("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertIn("xconvkernel.c", cm)
        self.assertIn("xmatmulkernel.c", cm)
        self.assertIn("xvectoropkernel.c", cm)


# ---------------------------------------------------------------------------
# Node-level structure checks
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsNodeStructure(unittest.TestCase):
    """Verify parsed node types and counts match what each model spec says."""

    def _nodes(self, name: str):
        p = _path(name)
        return OnnxGraph(p).nodes

    def _count(self, nodes, ntype):
        return sum(1 for n in nodes if isinstance(n, ntype))

    def test_relu_conv_matmul_node_types(self):
        nodes = self._nodes("mixed_all_relu_conv_matmul.onnx")
        self.assertEqual(len(nodes), 4)
        self.assertEqual(self._count(nodes, ScheduledNode), 2)
        self.assertEqual(self._count(nodes, ConvNode),      1)
        self.assertEqual(self._count(nodes, MatmulNode),    1)

    def test_conv_matmul_relu_node_types(self):
        nodes = self._nodes("mixed_all_conv_matmul_relu.onnx")
        self.assertEqual(len(nodes), 4)
        self.assertEqual(self._count(nodes, ConvNode),      1)
        self.assertEqual(self._count(nodes, MatmulNode),    1)
        self.assertEqual(self._count(nodes, ScheduledNode), 2)

    def test_norm_conv_project_node_types(self):
        nodes = self._nodes("mixed_all_norm_conv_project.onnx")
        self.assertEqual(len(nodes), 5)
        self.assertEqual(self._count(nodes, ConvNode),      1)
        self.assertEqual(self._count(nodes, MatmulNode),    1)
        self.assertEqual(self._count(nodes, ScheduledNode), 3)

    def test_matmul_relu_conv_node_types(self):
        nodes = self._nodes("mixed_all_matmul_relu_conv.onnx")
        self.assertEqual(len(nodes), 4)
        self.assertEqual(self._count(nodes, MatmulNode),    1)
        self.assertEqual(self._count(nodes, ConvNode),      1)
        self.assertEqual(self._count(nodes, ScheduledNode), 2)

    def test_skip_conv_matmul_node_types(self):
        nodes = self._nodes("mixed_all_skip_conv_matmul.onnx")
        self.assertEqual(len(nodes), 4)
        self.assertEqual(self._count(nodes, ConvNode),      1)
        self.assertEqual(self._count(nodes, MatmulNode),    1)
        self.assertEqual(self._count(nodes, ScheduledNode), 2)

    def test_two_conv_matmul_relu6_node_types(self):
        nodes = self._nodes("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertEqual(len(nodes), 6)
        self.assertEqual(self._count(nodes, ConvNode),      2)
        self.assertEqual(self._count(nodes, MatmulNode),    1)
        self.assertEqual(self._count(nodes, ScheduledNode), 3)

    def test_sub_matmul_conv_node_types(self):
        nodes = self._nodes("mixed_all_sub_matmul_conv.onnx")
        self.assertEqual(len(nodes), 5)
        self.assertEqual(self._count(nodes, ScheduledNode), 3)
        self.assertEqual(self._count(nodes, MatmulNode),    1)
        self.assertEqual(self._count(nodes, ConvNode),      1)

    def test_relu_conv_matmul_conv_geometry(self):
        """Conv node: IC=4, OC=8, 1×1 kernel, no bias."""
        nodes = self._nodes("mixed_all_relu_conv_matmul.onnx")
        conv = next(n for n in nodes if isinstance(n, ConvNode))
        self.assertEqual(conv.in_ch,  4)
        self.assertEqual(conv.out_ch, 8)
        self.assertEqual(conv.kh,     1)
        self.assertEqual(conv.kw,     1)
        self.assertFalse(conv.has_bias)

    def test_conv_matmul_relu_conv_geometry(self):
        """Conv node: IC=3, OC=8, 3×3 kernel, has_bias=True."""
        nodes = self._nodes("mixed_all_conv_matmul_relu.onnx")
        conv = next(n for n in nodes if isinstance(n, ConvNode))
        self.assertEqual(conv.in_ch,  3)
        self.assertEqual(conv.out_ch, 8)
        self.assertEqual(conv.kh,     3)
        self.assertEqual(conv.kw,     3)
        self.assertTrue(conv.has_bias)

    def test_skip_conv_matmul_matmul_batch(self):
        """MatMul on B[1,8,4,4] @ Wm[4,4]: batch=8, n=4, k=4, m=4."""
        nodes = self._nodes("mixed_all_skip_conv_matmul.onnx")
        mm = next(n for n in nodes if isinstance(n, MatmulNode))
        self.assertEqual(mm.batch, 8)
        self.assertEqual(mm.n, 4)
        self.assertEqual(mm.k, 4)
        self.assertEqual(mm.m, 4)

    def test_sub_matmul_conv_matmul_batch(self):
        """MatMul on Z1[1,4,4,8] @ Wm[8,8]: batch=4, n=4, k=8, m=8."""
        nodes = self._nodes("mixed_all_sub_matmul_conv.onnx")
        mm = next(n for n in nodes if isinstance(n, MatmulNode))
        self.assertEqual(mm.batch, 4)
        self.assertEqual(mm.n, 4)
        self.assertEqual(mm.k, 8)
        self.assertEqual(mm.m, 8)


# ---------------------------------------------------------------------------
# Tensor layouts — all intermediate tensors must be flat (no broadcast stride)
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsLayouts(unittest.TestCase):
    """All tensors in all-kernel models have flat layouts (gap=0, n_chunks=1).

    ConvNode outputs are NCHW-flat; VectorOP nodes upstream of Conv accept
    flat inputs; no broadcast VectorOP is present in any of these models.
    """

    def _gen(self, name: str) -> CodeGenerator:
        return _gen(name)

    def _assert_flat(self, gen, name):
        lay = gen._layouts[name]
        self.assertEqual(lay.n_chunks, 1, f"{name}: n_chunks should be 1")
        self.assertEqual(lay.gap,      0, f"{name}: gap should be 0")

    def test_relu_conv_matmul_all_flat(self):
        g = self._gen("mixed_all_relu_conv_matmul.onnx")
        for t in ("Z", "A", "B", "Y"):
            self._assert_flat(g, t)

    def test_conv_matmul_relu_all_flat(self):
        g = self._gen("mixed_all_conv_matmul_relu.onnx")
        for t in ("Z", "A", "B", "Y"):
            self._assert_flat(g, t)

    def test_norm_conv_project_all_flat(self):
        g = self._gen("mixed_all_norm_conv_project.onnx")
        for t in ("Z1", "Z2", "A", "B", "Y"):
            self._assert_flat(g, t)

    def test_matmul_relu_conv_all_flat(self):
        g = self._gen("mixed_all_matmul_relu_conv.onnx")
        for t in ("Z", "A", "B", "Y"):
            self._assert_flat(g, t)

    def test_skip_conv_matmul_all_flat(self):
        g = self._gen("mixed_all_skip_conv_matmul.onnx")
        for t in ("Z", "A", "B", "Y"):
            self._assert_flat(g, t)

    def test_two_conv_matmul_relu6_all_flat(self):
        g = self._gen("mixed_all_two_conv_matmul_relu6.onnx")
        for t in ("Z1", "A1", "Z2", "A2", "B", "Y"):
            self._assert_flat(g, t)

    def test_sub_matmul_conv_all_flat(self):
        g = self._gen("mixed_all_sub_matmul_conv.onnx")
        for t in ("Z1", "Z2", "A", "B", "Y"):
            self._assert_flat(g, t)

    def test_no_broadcast_io_map_entries(self):
        """No model has broadcast VectorOP → _broadcast_io_map() is empty."""
        for name in [
            "mixed_all_relu_conv_matmul.onnx",
            "mixed_all_conv_matmul_relu.onnx",
            "mixed_all_norm_conv_project.onnx",
            "mixed_all_matmul_relu_conv.onnx",
            "mixed_all_skip_conv_matmul.onnx",
            "mixed_all_two_conv_matmul_relu6.onnx",
            "mixed_all_sub_matmul_conv.onnx",
        ]:
            with self.subTest(model=name):
                bmap = _gen(name)._broadcast_io_map()
                self.assertEqual(bmap, {}, f"{name}: broadcast_io_map should be empty")

    def test_matmul_natural_calls_no_strides(self):
        """No broadcast downstream of any MatMul → all run_matmul strides are natural."""
        for name in [
            "mixed_all_relu_conv_matmul.onnx",
            "mixed_all_conv_matmul_relu.onnx",
            "mixed_all_norm_conv_project.onnx",
            "mixed_all_matmul_relu_conv.onnx",
            "mixed_all_skip_conv_matmul.onnx",
            "mixed_all_two_conv_matmul_relu6.onnx",
            "mixed_all_sub_matmul_conv.onnx",
        ]:
            with self.subTest(model=name):
                src = _gen(name).generate_source()
                # no row-strided decomposition: 4th arg to run_matmul != 1u for batch
                # simplest check: run_matmul_at() is never emitted
                self.assertNotIn("run_matmul_at(", src, f"{name}: no outer loop expected")


# ---------------------------------------------------------------------------
# Simulation output shapes and value constraints
# ---------------------------------------------------------------------------

@unittest.skipUnless(_all_models_exist(),
                     "Run test/gen_mixed_all_kernels_models.py first")
class TestMixedAllKernelsSimulate(unittest.TestCase):
    """_simulate() produces correct output shapes and respects activation bounds."""

    def _sim(self, name: str):
        g = _gen(name)
        return g._simulate()

    def test_relu_conv_matmul_output_shape(self):
        arrays = self._sim("mixed_all_relu_conv_matmul.onnx")
        self.assertEqual(list(arrays["Y"].shape), [1, 8, 8, 4])

    def test_conv_matmul_relu_output_shape(self):
        arrays = self._sim("mixed_all_conv_matmul_relu.onnx")
        self.assertEqual(list(arrays["Y"].shape), [1, 8, 8, 4])

    def test_norm_conv_project_output_shape(self):
        arrays = self._sim("mixed_all_norm_conv_project.onnx")
        self.assertEqual(list(arrays["Y"].shape), [1, 8, 8, 4])

    def test_matmul_relu_conv_output_shape(self):
        arrays = self._sim("mixed_all_matmul_relu_conv.onnx")
        self.assertEqual(list(arrays["Y"].shape), [1, 8, 8, 8])

    def test_skip_conv_matmul_output_shape(self):
        arrays = self._sim("mixed_all_skip_conv_matmul.onnx")
        self.assertEqual(list(arrays["Y"].shape), [1, 8, 4, 4])

    def test_two_conv_matmul_relu6_output_shape(self):
        arrays = self._sim("mixed_all_two_conv_matmul_relu6.onnx")
        self.assertEqual(list(arrays["Y"].shape), [1, 8, 8, 4])

    def test_sub_matmul_conv_output_shape(self):
        arrays = self._sim("mixed_all_sub_matmul_conv.onnx")
        self.assertEqual(list(arrays["Y"].shape), [1, 8, 4, 8])

    def test_relu_conv_matmul_output_nonneg(self):
        """MatMul follows a Relu, but output may go negative. Z (after Relu) must be ≥ 0."""
        arrays = self._sim("mixed_all_relu_conv_matmul.onnx")
        self.assertTrue((arrays["Z"] >= 0).all(), "Z after Relu must be non-negative")

    def test_conv_matmul_relu_final_output_nonneg(self):
        """Final Relu → Y ≥ 0."""
        arrays = self._sim("mixed_all_conv_matmul_relu.onnx")
        self.assertTrue((arrays["Y"] >= 0).all(), "Y after Relu must be non-negative")

    def test_matmul_relu_conv_relu6_bounds(self):
        """Final Relu6 → Y ∈ [0, 6]."""
        import numpy as np
        arrays = self._sim("mixed_all_matmul_relu_conv.onnx")
        y = arrays["Y"]
        self.assertTrue((y >= 0).all(),   "Relu6 output must be ≥ 0")
        self.assertTrue((y <= 6.01).all(), "Relu6 output must be ≤ 6")

    def test_two_conv_matmul_relu6_bounds(self):
        """Final Relu6 → Y ∈ [0, 6]."""
        arrays = self._sim("mixed_all_two_conv_matmul_relu6.onnx")
        y = arrays["Y"]
        self.assertTrue((y >= 0).all(),   "Relu6 output must be ≥ 0")
        self.assertTrue((y <= 6.01).all(), "Relu6 output must be ≤ 6")

    def test_sub_matmul_conv_relu6_bounds(self):
        """Final Relu6 → Y ∈ [0, 6]."""
        arrays = self._sim("mixed_all_sub_matmul_conv.onnx")
        y = arrays["Y"]
        self.assertTrue((y >= 0).all(),   "Relu6 output must be ≥ 0")
        self.assertTrue((y <= 6.01).all(), "Relu6 output must be ≤ 6")

    def test_norm_conv_project_has_all_intermediates(self):
        """Simulation must produce all intermediate tensors."""
        arrays = self._sim("mixed_all_norm_conv_project.onnx")
        for name in ("Z1", "Z2", "A", "B", "Y"):
            self.assertIn(name, arrays, f"intermediate {name} missing from simulation")

    def test_two_conv_model_has_all_intermediates(self):
        arrays = self._sim("mixed_all_two_conv_matmul_relu6.onnx")
        for name in ("Z1", "A1", "Z2", "A2", "B", "Y"):
            self.assertIn(name, arrays)


if __name__ == "__main__":
    unittest.main(verbosity=2)
