"""Tests for MatmulKernel scheduler integration — hardware-bound
validation and platform-JSON resolver.

The matmul-model ONNX files generated by ``gen_matmul_models.py`` are
exercised on hardware via ``run_remote_tests.py``; the corresponding
Python-side correctness is covered by ``test_mixed_kernel.py`` and
friends.  This module focuses specifically on rejecting layer
geometries the kernel cannot service (``k > kMaxK``) and on the
single-source-of-truth resolver that reads ``kernels.matmul`` from
the platform JSON.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.graph import OnnxGraph
from src.nodes import MatmulNode, SchedulerError


MODELS_DIR = os.path.join(os.path.dirname(__file__), "models")


def _matmul_model(name: str) -> str:
    return os.path.join(MODELS_DIR, name)


def _matmul_models_exist() -> bool:
    return (os.path.isfile(_matmul_model("mm_unsupported_k.onnx")) and
            os.path.isfile(_matmul_model("mm_k_at_limit.onnx")))


# ---------------------------------------------------------------------------
# MatmulNode hardware-bound validation
#
# kMaxK comes from platforms/<AXI_PLATFORM>.json (see _matmul_hw_config)
# and matches the kernel's compile-time ``a_buf[kTileN][kMaxK]`` row
# staging buffer.  A matmul with k > kMaxK has no runtime fallback —
# reject it at parse time with an error that names the bound and the
# JSON field to bump.
# ---------------------------------------------------------------------------

@unittest.skipUnless(_matmul_models_exist(),
                     "Run test/gen_matmul_models.py first")
class TestMatmulNodeHardwareBounds(unittest.TestCase):
    """MatmulNode rejects matmuls the kernel cannot service."""

    def test_k_too_large_raises(self):
        """k=2049 violates kMaxK=2048."""
        with self.assertRaises(SchedulerError) as cm:
            OnnxGraph(_matmul_model("mm_unsupported_k.onnx"))
        msg = str(cm.exception)
        self.assertIn("k=2049", msg)
        self.assertIn("kMaxK", msg)

    def test_k_at_limit_parses(self):
        """k=2048 == kMaxK must parse — bound is `≤`, not `<`."""
        g = OnnxGraph(_matmul_model("mm_k_at_limit.onnx"))
        sn = g.nodes[0]
        self.assertIsInstance(sn, MatmulNode)
        self.assertEqual(sn.k, 2048)


class TestMatmulHwConfigResolver(unittest.TestCase):
    """The hardware-bound resolver reads from the platform JSON
    (platforms/<AXI_PLATFORM>.json), the same source the C++ CMake build
    consumes via ``matmul_load_constants()``.  Tests use the public
    ``resolve()`` function so failure paths can be probed without
    reloading the module — that would replace the
    ``MatmulHwConfigError`` class object and break ``assertRaises``."""

    def _platforms_dir(self):
        from pathlib import Path
        return (Path(__file__).resolve().parent.parent.parent / "platforms")

    def test_constants_match_kv260_json(self):
        """Resolved values match platforms/kv260.json's kernels.matmul —
        guards against drift between the Python validator and the JSON
        the C++ build reads."""
        import json

        from src._matmul_hw_config import MATMUL_MAX_K
        with (self._platforms_dir() / "kv260.json").open() as f:
            cfg = json.load(f)["kernels"]["matmul"]
        self.assertEqual(MATMUL_MAX_K, cfg["max_k"])

    def test_resolve_alternate_platform_picks_up_overrides(self):
        """``resolve('<name>')`` reads ``platforms/<name>.json`` — same
        mechanism the CMake build uses when ``-DAXI_PLATFORM=<name>``
        is passed."""
        import json
        from src._matmul_hw_config import resolve

        alt = self._platforms_dir() / "_test_matmul_override.json"
        alt.write_text(json.dumps({
            "description": "test-only override",
            "part": "x", "clock": 100,
            "kernels": {"matmul": {
                "tile_n": 4, "tile_m": 16, "tile_k": 256,
                "max_k": 1024,                      # <-- the override
            }},
        }))
        try:
            cfg = resolve("_test_matmul_override")
            self.assertEqual(cfg["MATMUL_MAX_K"], 1024)
        finally:
            alt.unlink(missing_ok=True)

    def test_missing_platform_file_raises(self):
        """``resolve()`` with an unknown platform name must error loudly
        rather than silently fall back to defaults."""
        from src._matmul_hw_config import MatmulHwConfigError, resolve

        with self.assertRaises(MatmulHwConfigError) as cm:
            resolve("_does_not_exist_xyzzy_matmul")
        self.assertIn("not found", str(cm.exception))

    def test_missing_kernels_matmul_section_raises(self):
        """A platform JSON with no ``kernels.matmul`` object must error —
        no silent default fallback."""
        import json
        from src._matmul_hw_config import MatmulHwConfigError, resolve

        bad = self._platforms_dir() / "_test_no_matmul_section.json"
        bad.write_text(json.dumps({"description": "no kernels section",
                                   "part": "x", "clock": 100}))
        try:
            with self.assertRaises(MatmulHwConfigError) as cm:
                resolve("_test_no_matmul_section")
            self.assertIn("kernels.matmul", str(cm.exception))
        finally:
            bad.unlink(missing_ok=True)

    def test_missing_required_field_raises(self):
        """A platform JSON missing the mandatory ``kernels.matmul.max_k``
        field must error and name the missing field."""
        import json
        from src._matmul_hw_config import MatmulHwConfigError, resolve

        bad = self._platforms_dir() / "_test_matmul_missing_field.json"
        bad.write_text(json.dumps({
            "description": "missing max_k",
            "part": "x", "clock": 100,
            "kernels": {"matmul": {
                "tile_n": 4, "tile_m": 16, "tile_k": 256,
                # max_k deliberately absent
            }},
        }))
        try:
            with self.assertRaises(MatmulHwConfigError) as cm:
                resolve("_test_matmul_missing_field")
            self.assertIn("max_k", str(cm.exception))
        finally:
            bad.unlink(missing_ok=True)


if __name__ == "__main__":
    unittest.main()
