#!/usr/bin/env python3
"""
inference_scheduler.py — ONNX-to-VectorOPKernel project generator

Parses an ONNX model and writes a CMake project that compiles a static
library implementing the full inference loop on the Xilinx KV260, using
VectorOPKernel invocations via the XVectoropkernel driver API.

Supported ONNX operators:
  Add, Sub, Mul, Div, Relu, Clip(min=0, max=6)

Output project layout:
  <out_dir>/
  ├── CMakeLists.txt              INFERENCE_TARGET=BARE_METAL|LINUX
  ├── include/
  │   └── inference.h             public API: Data_t, sizes, init/run
  ├── src/
  │   └── inference.c             generated inference loop (dual-target)
  └── driver/                     XVectoropkernel driver sources
      ├── xvectoropkernel.h       ┐
      ├── xvectoropkernel_hw.h    │  copied from --driver-dir,
      ├── xvectoropkernel.c       │  or left empty with a README
      ├── xvectoropkernel_sinit.c │ (bare-metal)
      └── xvectoropkernel_linux.c ┘ (Linux)

Usage:
  python inference_scheduler.py model.onnx
  python inference_scheduler.py model.onnx --out-dir ./my_project
  python inference_scheduler.py model.onnx --out-dir ./my_project \\
      --driver-dir ../build/kv260/vadd_kv260/solution1/impl/ip/\\
                   drivers/VectorOPKernel_v1_0/src
"""

import argparse
import os
import shutil
import sys

# Allow running from the project root without installing the package
sys.path.insert(0, os.path.dirname(__file__))

from src.graph            import OnnxGraph
from src.codegen          import CodeGenerator
from src.codegen._simulate import LARGE_EXPECTED_THRESHOLD
from src.nodes            import SchedulerError
from src.tensor           import LARGE_WEIGHT_THRESHOLD


# Driver file lists — CMakeLists.txt selects sinit.c or linux.c at
# configure time based on INFERENCE_TARGET; both are copied so the project
# works for either target without re-running the scheduler.
_VECTOROP_DRIVER_FILES = [
    "xvectoropkernel.h",
    "xvectoropkernel_hw.h",
    "xvectoropkernel.c",
    "xvectoropkernel_sinit.c",   # BARE_METAL target
    "xvectoropkernel_linux.c",   # LINUX target
]

_MATMUL_DRIVER_FILES = [
    "xmatmulkernel.h",
    "xmatmulkernel_hw.h",
    "xmatmulkernel.c",
    "xmatmulkernel_sinit.c",     # BARE_METAL target
    "xmatmulkernel_linux.c",     # LINUX target
]

# Keep the old name as an alias for backwards compatibility with tests
_DRIVER_FILES = _VECTOROP_DRIVER_FILES

_VECTOROP_DRIVER_README = """\
# driver/

Place XVectoropkernel driver sources here before building.

Required files:
  xvectoropkernel.h
  xvectoropkernel_hw.h
  xvectoropkernel.c
  xvectoropkernel_sinit.c   (used by INFERENCE_TARGET=BARE_METAL)
  xvectoropkernel_linux.c   (used by INFERENCE_TARGET=LINUX)

These are generated by Vitis HLS synthesis. Copy them from:

  <axi_demo>/build/kv260/vadd_kv260/solution1/impl/ip/
             drivers/VectorOPKernel_v1_0/src/

or run from the axi_demo build directory:

  make synthesize_kv260

then re-run inference_scheduler.py with:

  --driver-dir <axi_demo>/build/kv260/vadd_kv260/solution1/impl/ip/\\
               drivers/VectorOPKernel_v1_0/src
"""

_MATMUL_DRIVER_README = """\
# driver/

Place XMatmulkernel driver sources here before building.

Required files:
  xmatmulkernel.h
  xmatmulkernel_hw.h
  xmatmulkernel.c
  xmatmulkernel_sinit.c   (used by INFERENCE_TARGET=BARE_METAL)
  xmatmulkernel_linux.c   (used by INFERENCE_TARGET=LINUX)

These are generated by Vitis HLS synthesis. Copy them from:

  <axi_demo>/build/kv260/matmul_kv260/solution1/impl/ip/
             drivers/MatmulKernel_v1_0/src/

or run from the axi_demo build directory:

  make synthesize_kv260   (builds both VectorOP and Matmul IPs)

then re-run inference_scheduler.py with:

  --driver-dir <axi_demo>/build/kv260/matmul_kv260/solution1/impl/ip/\\
               drivers/MatmulKernel_v1_0/src
"""

# Keep the old name as an alias
_DRIVER_README = _VECTOROP_DRIVER_README


def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="Generate a VectorOPKernel inference project from an ONNX model.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "model",
        metavar="model.onnx",
        help="Input ONNX model file",
    )
    p.add_argument(
        "--out-dir",
        metavar="DIR",
        default=None,
        help=(
            "Output project directory (default: ./<model_stem>_inference/). "
            "Created if absent; existing files are overwritten."
        ),
    )
    p.add_argument(
        "--driver-dir",
        metavar="DIR",
        default=None,
        help=(
            "Path to the XVectoropkernel driver source directory "
            "(contains xvectoropkernel.c, .h, _hw.h, _sinit.c, _linux.c). "
            "If omitted, driver/ is left empty with a README."
        ),
    )
    p.add_argument(
        "--embed-large-weights",
        action="store_true",
        default=False,
        help=(
            f"Embed all weight tensors as C arrays in inference.c, even those "
            f"exceeding the {LARGE_WEIGHT_THRESHOLD}-element threshold that would "
            f"normally be written to external weights/*.dat files. "
            f"Produces a larger but fully self-contained C file."
        ),
    )
    p.add_argument(
        "--embed-large-expected",
        action="store_true",
        default=False,
        help=(
            f"Embed all GT expected arrays as C arrays in test_inference.c, even "
            f"those exceeding the {LARGE_EXPECTED_THRESHOLD}-element threshold that "
            f"would normally be written to external expected/*.dat files. "
            f"Produces a larger but fully self-contained test file."
        ),
    )
    return p.parse_args(argv)


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def _copy_driver(src_dir: str, dst_dir: str, files: list = None) -> list:
    """
    Copy driver files from src_dir into dst_dir.
    Returns list of filenames that were not found (warnings).
    files defaults to _VECTOROP_DRIVER_FILES for backwards compatibility.
    """
    if files is None:
        files = _VECTOROP_DRIVER_FILES
    os.makedirs(dst_dir, exist_ok=True)
    missing = []
    for fname in files:
        src = os.path.join(src_dir, fname)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(dst_dir, fname))
        else:
            missing.append(fname)
    return missing


def main(argv=None):
    args = parse_args(argv)

    # ---------------------------------------------------------------- #
    # 1. Resolve output directory                                       #
    # ---------------------------------------------------------------- #
    if args.out_dir is None:
        stem    = os.path.splitext(os.path.basename(args.model))[0]
        out_dir = os.path.join(os.getcwd(), f"{stem}_inference")
    else:
        out_dir = os.path.abspath(args.out_dir)

    # ---------------------------------------------------------------- #
    # 2. Parse and validate the ONNX model                             #
    # ---------------------------------------------------------------- #
    try:
        graph = OnnxGraph(args.model)
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except SchedulerError as e:
        print(f"error: unsupported graph — {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"error: failed to load ONNX model: {e}", file=sys.stderr)
        return 1

    # ---------------------------------------------------------------- #
    # 3. Print graph summary                                            #
    # ---------------------------------------------------------------- #
    inputs  = graph.input_tensors
    outputs = graph.output_tensors
    nodes   = graph.nodes

    print(f"Model      : {args.model}", file=sys.stderr)
    print(f"Inputs     : {[f'{t.onnx_name}{t.shape}' for t in inputs]}", file=sys.stderr)
    print(f"Outputs    : {[f'{t.onnx_name}{t.shape}' for t in outputs]}", file=sys.stderr)
    print(f"Nodes      : {len(nodes)}", file=sys.stderr)
    for sn in nodes:
        in_shapes = [str(t.shape) for t in sn.inputs]
        print(
            f"  [{sn.index:3d}] {sn.onnx_node.op_type:<12}"
            f" {' x '.join(in_shapes)} -> {sn.output.shape}",
            file=sys.stderr,
        )
    print(f"Output dir : {out_dir}", file=sys.stderr)

    # ---------------------------------------------------------------- #
    # 4. Generate code                                                  #
    # ---------------------------------------------------------------- #
    try:
        gen        = CodeGenerator(graph=graph, model_path=args.model,
                                   embed_large_weights=args.embed_large_weights,
                                   embed_large_expected=args.embed_large_expected)
        header     = gen.generate_header()
        source     = gen.generate_source()
        buf_impl   = gen.generate_buf_impl()
        cmake      = gen.generate_cmake()
        setup_sh   = gen.generate_setup_script()
        test_src   = gen.generate_test()
    except SchedulerError as e:
        print(f"error: code generation failed — {e}", file=sys.stderr)
        return 1

    # ---------------------------------------------------------------- #
    # 5. Write project files                                            #
    # ---------------------------------------------------------------- #
    _write(os.path.join(out_dir, "CMakeLists.txt"),              cmake)
    _write(os.path.join(out_dir, "include", "inference.h"),      header)
    _write(os.path.join(out_dir, "src",     "inference.c"),      source)
    _write(os.path.join(out_dir, "src",     "inference_buf.c"),  buf_impl)
    _write(os.path.join(out_dir, "scripts", "check_inference_setup.sh"), setup_sh)
    _write(os.path.join(out_dir, "test",    "test_inference.c"), test_src)

    # ---------------------------------------------------------------- #
    # 5b. External weight .dat files (large tensors)                    #
    # ---------------------------------------------------------------- #
    large_weights = gen.large_weight_tensors
    if large_weights:
        weights_dir = os.path.join(out_dir, "weights")
        os.makedirs(weights_dir, exist_ok=True)
        for t in large_weights:
            dat_path = os.path.join(weights_dir, f"{t.c_name}.dat")
            with open(dat_path, "wb") as f:
                f.write(gen.generate_weight_dat(t))
        print(f"Weights    : {len(large_weights)} large weight(s) written to"
              f" {weights_dir}/", file=sys.stderr)

    # ---------------------------------------------------------------- #
    # 5c. External expected GT .dat files (large outputs)               #
    # ---------------------------------------------------------------- #
    large_expected = gen.large_expected_tensors
    if large_expected:
        expected_dir = os.path.join(out_dir, "expected")
        os.makedirs(expected_dir, exist_ok=True)
        for t in large_expected:
            dat_path = os.path.join(expected_dir, f"{t.c_name}.dat")
            with open(dat_path, "wb") as f:
                f.write(gen.generate_expected_dat(t))
        print(f"Expected   : {len(large_expected)} large GT array(s) written to"
              f" {expected_dir}/", file=sys.stderr)

    # ---------------------------------------------------------------- #
    # 6. Driver sources                                                 #
    # ---------------------------------------------------------------- #
    # Select the right driver file list and README based on model type.
    has_matmul = gen._has_matmul_nodes
    driver_files  = _MATMUL_DRIVER_FILES  if has_matmul else _VECTOROP_DRIVER_FILES
    driver_readme = _MATMUL_DRIVER_README if has_matmul else _VECTOROP_DRIVER_README

    driver_dir = os.path.join(out_dir, "driver")
    if args.driver_dir:
        src_dir = os.path.abspath(args.driver_dir)
        if not os.path.isdir(src_dir):
            print(
                f"error: --driver-dir '{src_dir}' is not a directory",
                file=sys.stderr,
            )
            return 1
        missing = _copy_driver(src_dir, driver_dir, driver_files)
        copied  = len(driver_files) - len(missing)
        print(f"Driver     : copied {copied}/{len(driver_files)} files from {src_dir}",
              file=sys.stderr)
        if missing:
            print("  warning: missing files:", file=sys.stderr)
            for f in missing:
                print(f"    {f}", file=sys.stderr)
            print("  Project will not build until driver/ is complete.",
                  file=sys.stderr)
    else:
        os.makedirs(driver_dir, exist_ok=True)
        with open(os.path.join(driver_dir, "README.md"), "w") as f:
            f.write(driver_readme)
        print("Driver     : driver/ is empty — see driver/README.md",
              file=sys.stderr)

    # ---------------------------------------------------------------- #
    # 7. Report                                                         #
    # ---------------------------------------------------------------- #
    print("", file=sys.stderr)
    print("Generated project:", file=sys.stderr)
    report_items = [
        "CMakeLists.txt",
        "include/inference.h",
        "src/inference.c",
        "src/inference_buf.c",
        "test/test_inference.c",
        "scripts/check_inference_setup.sh",
        "driver/",
    ]
    if large_weights:
        report_items.append("weights/")
    if large_expected:
        report_items.append("expected/")
    for rel in report_items:
        print(f"  {os.path.join(out_dir, rel)}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
